package com.ironmonone.editor

import java.lang.reflect.Method
import java.util.Locale

/**
 * The randomizer editor's model, generated by reflection over the engine's own
 * `Settings` class — the same approach UPR-Android ships. Reflection rather than a
 * hand-kept option list because the hand-kept list is exactly the kind of thing that
 * goes stale the day the engine is updated: whatever the vendored engine actually
 * supports is, by construction, what the editor shows.
 *
 * Three option shapes cover the surface (147 setters): booleans, bounded ints, and the
 * 22 mode enums. Anything else (rom name, custom names, gen restrictions) is engine
 * plumbing, not a player choice, and is deliberately not exposed.
 */
sealed interface Option {
    val id: String          // property name, e.g. "randomizeMovePowers"
    val label: String       // prettified, e.g. "Randomize move powers"
    val section: Section

    data class Bool(
        override val id: String, override val label: String, override val section: Section,
        val get: (Any) -> Boolean, val set: (Any, Boolean) -> Unit,
    ) : Option

    data class IntValue(
        override val id: String, override val label: String, override val section: Section,
        val get: (Any) -> Int, val set: (Any, Int) -> Unit,
    ) : Option

    data class Choice(
        override val id: String, override val label: String, override val section: Section,
        val values: List<String>,
        val get: (Any) -> String, val set: (Any, String) -> Unit,
    ) : Option
}

/** The ZX 4.6.1 sections, brief section 6. */
enum class Section(val title: String) {
    TRAITS("Pokémon Traits"),
    STARTERS("Starters, Statics & Trades"),
    MOVES("Moves & Movesets"),
    TRAINERS("Foe Pokémon / Trainers"),
    WILD("Wild Pokémon"),
    TMHM("TM/HM & Tutors"),
    ITEMS("Items"),
    MISC("Misc Tweaks"),
}

object SettingsReflector {

    /** Excluded: engine plumbing a player never sets directly. */
    private val EXCLUDED = setOf(
        "romName", "customNames", "currentRestrictions", "currentMiscTweaks",
        "updatedFromOldVersion",
    )

    fun options(cls: Class<*>): List<Option> {
        val methods = cls.methods
        val getters = HashMap<String, Method>()
        methods.forEach { m ->
            if (m.parameterCount == 0) {
                when {
                    m.name.startsWith("is") && m.returnType == Boolean::class.javaPrimitiveType ->
                        getters[m.name.removePrefix("is").decap()] = m
                    m.name.startsWith("get") -> getters[m.name.removePrefix("get").decap()] = m
                }
            }
        }

        val out = ArrayList<Option>()
        methods.filter { it.name.startsWith("set") && it.parameterCount == 1 }
            .sortedBy { it.name }
            .forEach { setter ->
                val id = setter.name.removePrefix("set").decap()
                if (id in EXCLUDED) return@forEach
                val getter = getters[id] ?: return@forEach
                val type = setter.parameterTypes[0]
                val label = prettify(id)
                val section = sectionOf(id)
                when {
                    type == Boolean::class.javaPrimitiveType -> out += Option.Bool(
                        id, label, section,
                        get = { s -> getter.invoke(s) as Boolean },
                        set = { s, v -> setter.invoke(s, v) },
                    )
                    type == Int::class.javaPrimitiveType -> out += Option.IntValue(
                        id, label, section,
                        get = { s -> getter.invoke(s) as Int },
                        set = { s, v -> setter.invoke(s, v) },
                    )
                    // other types (String, boolean[], objects): plumbing, skipped here;
                    // mode enums are handled below because their setters are PRIVATE.
                }
            }

        // The 22 mode enums. Public surface is `getXxxMod(): SomeMod` plus a public
        // `setXxxMod(boolean...)`; the enum-typed setter is private. We call the
        // private one directly - this is our own vendored code, not framework API, so
        // setAccessible is legitimate on Android too.
        methods.filter {
            it.parameterCount == 0 && it.name.startsWith("get") &&
                it.returnType.isEnum && it.returnType.enclosingClass == cls
        }.sortedBy { it.name }.forEach { getter ->
            val id = getter.name.removePrefix("get").decap()
            if (id in EXCLUDED) return@forEach
            val type = getter.returnType
            val enumSetter = runCatching {
                cls.getDeclaredMethod("set" + id.cap(), type)
                    .apply { isAccessible = true }
            }.getOrNull() ?: return@forEach
            val values = type.enumConstants.map { (it as Enum<*>).name }
            out += Option.Choice(
                id, prettify(id), sectionOf(id), values,
                get = { s -> (getter.invoke(s) as Enum<*>).name },
                set = { s, v ->
                    @Suppress("UNCHECKED_CAST")
                    val e = java.lang.Enum.valueOf(type as Class<out Enum<*>>, v)
                    enumSetter.invoke(s, e)
                },
            )
        }
        // Order by the DESKTOP RANDOMIZER's own control order, not
        // alphabetically.
        //
        // Reflection hands fields back in an arbitrary order, which put
        // dependent controls ABOVE the master enum they depend on - "Abilities
        // follow evolutions" rendered before "Abilities mod", which reads as
        // nonsense and hides the one control that decides whether the rest do
        // anything.
        //
        // UPR_ORDER is generated from NewRandomizerGUI.form (visual order)
        // joined to createSettingsFromState() (which control writes which
        // field) by tools/extract_upr_order.py. Anything the desktop GUI does
        // not expose sorts to the end, alphabetically, rather than vanishing.
        return out.sortedWith(
            compareBy({ UPR_ORDER[it.id] ?: Int.MAX_VALUE }, { it.id }),
        )
    }

    /** Read a two-column generated TSV resource into a map. */
    private fun tsv(name: String): Map<String, String> {
        val stream = SettingsReflector::class.java.classLoader
            ?.getResourceAsStream(name) ?: return emptyMap()
        return stream.bufferedReader().useLines { lines ->
            lines.filterNot { it.startsWith("#") || it.isBlank() }
                .mapNotNull {
                    val parts = it.split('	')
                    if (parts.size >= 2) parts[0] to parts[1] else null
                }
                .toMap()
        }
    }

    /**
     * The randomizer's OWN description for a setting, or null.
     *
     * Generated from Bundle.properties by tools/extract_upr.py. 122 of the 138
     * fields have one; the rest are null and the editor shows nothing rather
     * than inventing an explanation for them.
     */
    private val HELP: Map<String, String> by lazy { tsv("upr-help.tsv") }

    fun helpFor(id: String): String? = HELP[id]

    /**
     * A rule that greys a control out: this field is disabled while [whenField]
     * equals [equalsValue].
     */
    data class Gate(val whenField: String, val equalsValue: String)

    /**
     * Gating rules from the desktop's enableOrDisableSubControls().
     *
     * PARTIAL BY DESIGN - only the single-condition blocks are extracted, so a
     * control with a compound condition simply stays enabled. That direction is
     * the safe one: a missing rule leaves a control usable, a wrong rule greys
     * out something that should work and looks like a broken editor.
     */
    private val GATES: Map<String, Gate> by lazy {
        val stream = SettingsReflector::class.java.classLoader
            ?.getResourceAsStream("upr-gating.tsv") ?: return@lazy emptyMap()
        stream.bufferedReader().useLines { lines ->
            lines.filterNot { it.startsWith("#") || it.isBlank() }
                .mapNotNull {
                    val p = it.split('	')
                    if (p.size >= 3) p[0] to Gate(p[1], p[2]) else null
                }
                .toMap()
        }
    }

    fun gateFor(id: String): Gate? = GATES[id]

    /**
     * Settings the desktop hides for an entire generation, e.g. everything
     * mega-evolution on a Gen 3 game.
     *
     * Only capabilities with a literal return are listed (see
     * tools/extract_upr_support.py), so anything absent is SHOWN. Missing a
     * rule leaves a usable control on screen; a wrong rule hides something the
     * game supports, which is the worse failure.
     */
    private val UNSUPPORTED: Set<Pair<String, String>> by lazy {
        val stream = SettingsReflector::class.java.classLoader
            ?.getResourceAsStream("upr-unsupported.tsv") ?: return@lazy emptySet()
        stream.bufferedReader().useLines { lines ->
            lines.filterNot { it.startsWith("#") || it.isBlank() }
                .mapNotNull {
                    val p = it.split('	')
                    if (p.size >= 2) p[0] to p[1] else null
                }
                .toSet()
        }
    }

    /**
     * True when [generation] cannot use this setting at all.
     *
     * Accepts the APP's own names as well as the table's. The table is keyed
     * GEN3/GEN4 (the randomizer's generations) while the app's enum is
     * GBA3/NDS4, and passing one where the other was expected matched nothing
     * and silently disabled the whole feature - it looked like it worked.
     */
    fun unsupportedIn(id: String, generation: String?): Boolean {
        val g = when (generation) {
            null -> return false
            "GBA3" -> "GEN3"
            "NDS4" -> "GEN4"
            else -> generation
        }
        return (id to g) in UNSUPPORTED
    }

    /** settings-field -> position, from the desktop GUI. See the sort above. */
    private val UPR_ORDER: Map<String, Int> by lazy {
        val stream = SettingsReflector::class.java.classLoader
            ?.getResourceAsStream("upr-order.tsv")
            ?: return@lazy emptyMap()
        stream.bufferedReader().useLines { lines ->
            lines.filterNot { it.startsWith("#") || it.isBlank() }
                .mapIndexedNotNull { i, line ->
                    line.substringBefore('	').takeIf { it.isNotBlank() }?.let { it to i }
                }
                .toMap()
        }
    }

    fun bySection(cls: Class<*>): Map<Section, List<Option>> =
        options(cls).groupBy { it.section }.toSortedMap(compareBy { it.ordinal })

    /**
     * Section routing by name keyword. Longest/most-specific keywords first; MISC is
     * the fallback rather than a guess, so nothing is silently hidden.
     */
    private fun sectionOf(id: String): Section {
        val n = id.lowercase(Locale.ROOT)
        return when {
            listOf("starter", "static", "trade", "totem", "ally", "aura")
                .any { n.contains(it) } -> Section.STARTERS
            listOf("trainer", "rival", "boss", "important", "regular", "swapmegaevos")
                .any { n.contains(it) } -> Section.TRAINERS
            listOf("wild", "catchrate", "areabased", "encounter")
                .any { n.contains(it) } -> Section.WILD
            listOf("tmshms", "tms", "hms", "tutor", "compat", "movetutor", "fullhmcompat")
                .any { n.contains(it) } -> Section.TMHM
            listOf("item", "shop", "pickup").any { n.contains(it) } -> Section.ITEMS
            listOf("move", "moveset").any { n.contains(it) } -> Section.MOVES
            listOf(
                "basestat", "stat", "exp", "type", "abilit", "evo", "evolution",
                "legendar", "pokemonpalette", "dualtype",
            ).any { n.contains(it) } -> Section.TRAITS
            else -> Section.MISC
        }
    }

    /** "randomizeMovePowers" -> "Randomize move powers"; keeps acronyms readable. */
    fun prettify(id: String): String {
        val words = Regex("(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
            .split(id)
            .joinToString(" ") { it.lowercase(Locale.ROOT) }
        return words.replaceFirstChar { it.uppercase(Locale.ROOT) }
            .replace(Regex("\\b(tm|hm|tms|hms|exp|hp|pp|bst|wp)\\b", RegexOption.IGNORE_CASE)) {
                it.value.uppercase(Locale.ROOT)
            }
    }

    /** Enum constant "RANDOM_EVERY_LEVEL" -> "Random every level". */
    fun prettifyEnum(name: String): String =
        name.lowercase(Locale.ROOT).replace('_', ' ')
            .replaceFirstChar { it.uppercase(Locale.ROOT) }

    private fun String.decap() = replaceFirstChar { it.lowercase(Locale.ROOT) }
    private fun String.cap() = replaceFirstChar { it.uppercase(Locale.ROOT) }
}
