package com.ironmonone.tracker.nds

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * gen5/items.tsv is generated by tools/extract_gen5_data.py from the
 * reference's ItemData.GEN_5_ITEMS, key by key. It used to be a copy of
 * the Gen 4 table, so every Gen 5 item (Drives, Gems, the Casteliacone)
 * showed as "#id" on the panel. These pins are the reference's own names.
 */
class Gen5ItemsTest {
    private val items: Map<Int, String> =
        javaClass.getResourceAsStream("/gen5/items.tsv")!!.bufferedReader().readLines()
            .filter { it.isNotBlank() }.associate { l -> val (id, name) = l.split('\t', limit = 2); id.toInt() to name }

    @Test
    fun `the Gen 5 table carries the reference's Gen 5 items, not Gen 4's`() {
        assertTrue(items.size >= 600, "only ${items.size} rows: still the Gen 4 seed?")
        assertEquals("Douse Drive", items[116])          // '???' in the Gen 4 table
        assertEquals("RageCandyBar", items[504])
        assertEquals("Balm Mushroom", items[580])
        assertEquals("Casteliacone", items[591])
        assertEquals("Gram 3", items[625])
        assertEquals("Paralyze Heal", items[22], "Gen 5 spelling, per the reference's GEN_5_ITEMS")
        assertTrue(items.values.none { it == "???" || it.isBlank() })
        assertTrue(0 !in items, "id 0 is 'no item' and the panel draws '-' for it")
    }
}
