"""Turn the community rulesets' published settings strings into a table the
generator can eat, the way parse_gist.py does for the official page.

Inputs, saved in tools/upr-settings/community/ (fetched 2026-09-29):
  ironmon-journey-rnqs-files.md   IronMON Journey strings, UTDZac's gist
                                  7c51734eed353779f1653217413dd05e (revision 9314ebb1, 2026-02-17)
  Chaos Kaizo Ironmon Rules.md    Chaos Kaizo, UTDZac's gist c8c3a84553840f8eabb063be80a33ee7
                                  (revision 22dbe34f, 2023-09-20)
  evo-kaizo-puyAqPyt.txt          Evo Kaizo, https://pastebin.com/raw/puyAqPyt (undated, author not named)
  SurvivalRevival-README.md       Survival Revival, Reimittv/SurvivalRevivalIronMON README
                                  (commit 3fec370d, 2026-02-21)
Output: community.tsv, the same columns as strings.tsv.

Journey's X/Y and Omega Ruby/Alpha Sapphire strings are dropped: no 3DS core.
The Survival Revival string carries 8 bytes that ZX 4.6.1 does not read; it is
flagged EXTRA_TWEAKS and PresetGenerator reads it as the tool that wrote it
did (something-smart/ironmon-randomizer, see there).

Deterministic: run it twice and the TSV is identical.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "community"
OUT = HERE / "community.tsv"
B64 = re.compile(r"(\d{3}[A-Za-z0-9+/=]{40,})")

JOURNEY = {   # heading in the Journey gist -> the tag RnqsInfo reads
    "Gen 3: Fire Red, Leaf Green": "FRLG",
    "Gen 3: Emerald, Ruby, Sapphire": "RSE",
    "Gen 4: Heart Gold, Soul Silver": "HGSS",
    "Gen 4: Platinum, Diamond, Pearl": "DPPt",
    "Gen 5: Black, White": "BW",
    "Gen 5: Black 2, White 2": "B2W2",
}
CHAOS = {"Fire Red / Leaf Green": "FRLG", "Ruby / Sapphire / Emerald": "RSE"}


def journey(rows):
    text = (SRC / "ironmon-journey-rnqs-files.md").read_text(encoding="utf-8")
    body = text.split("## Setting Strings", 1)[1]
    for block in re.split(r"^### ", body, flags=re.M)[1:]:
        head, _, rest = block.partition("\n")
        tag = JOURNEY.get(head.strip())
        m = B64.search(rest)
        if tag and m:
            rows.append((tag, "Ironmon Journey", "OK", m.group(1), "Journey gist: " + head.strip()))


def chaos(rows):
    text = (SRC / "Chaos Kaizo Ironmon Rules.md").read_text(encoding="utf-8")
    for m in re.finditer(r"^#### Randomizer Settings String for (.+?):\s*\n`(\d{3}[A-Za-z0-9+/=]+)`", text, re.M):
        tag = CHAOS.get(m.group(1).strip())
        if tag:
            rows.append((tag, "Chaos Kaizo", "OK", m.group(2), "Chaos gist: " + m.group(1).strip()))


def evo(rows):
    text = (SRC / "evo-kaizo-puyAqPyt.txt").read_text(encoding="utf-8")
    m = re.search(r"Setting String if you want to try - (\d{3}[A-Za-z0-9+/=]+)", text)
    if m:
        rows.append(("FRLG", "Evo Kaizo", "OK", m.group(1), "pastebin puyAqPyt"))


def revival(rows):
    text = (SRC / "SurvivalRevival-README.md").read_text(encoding="utf-8")
    body = text.split("## Randomizer Settings Strings", 1)[1]
    m = re.search(r"^### Fire Red / Leaf Green\s*\n(\d{3}[A-Za-z0-9+/=]+)", body, re.M)
    if m:
        rows.append(("FRLG", "Survival Revival", "EXTRA_TWEAKS", m.group(1), "Survival Revival README: Fire Red / Leaf Green"))


def main():
    rows = []
    for part in (journey, chaos, evo, revival):
        part(rows)
    with OUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# GENERATED by tools/upr-settings/parse_community.py from community/.\n")
        f.write("# tag\tmode\tflag\tstring\tsection\n")
        for r in rows:
            f.write("\t".join(r) + "\n")
    for r in rows:
        print("%-5s %s" % (r[0], r[1]))
    print("%d rows -> %s" % (len(rows), OUT.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
