"""Turn the official IronMON settings page into a table the generator can eat.

Input:  official-settings.md - the raw gist, fetched 2026-09-05 from
        https://gist.github.com/UTDZac/a147c497424dfbd537d8c4b0c22b5621
Output: strings.tsv - one row per (game tag, mode, settings string, section)

The page groups games under "## RED / BLUE / YELLOW" style headings and puts
the strings in ``` blocks under "#### Settings Strings" - a label line, then
the base64 line. Some labels name several modes at once ("Standard /
Ultimate / Kaizo"); those become one row per mode, same string.

Only the "4.6.0 and higher" blocks are taken where a page offers two; the
older "4.4.0" blocks are for a randomizer we do not ship. Gen 6 and 7 are
parsed and then dropped: no 3DS core. Gen 1 is parsed but flagged TWO_PART,
because its page requires randomizing twice (PART 1, then PART 2 over the
result) or a third-party patch, neither of which the app does yet.

Deterministic: run it twice and the TSV is identical.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "official-settings.md"
OUT = HERE / "strings.tsv"

# gist heading -> the tag RnqsInfo reads out of a file name
GAMES = {
    "RED / BLUE / YELLOW": "RBY",
    "GOLD / SILVER / CRYSTAL": "GSC",
    "FIRE RED / LEAF GREEN": "FRLG",
    "RUBY / SAPPHIRE / EMERALD": "RSE",
    "HEART GOLD / SOUL SILVER": "HGSS",
    "DIAMOND / PEARL / PLATINUM": "DPPt",
    "BLACK / WHITE": "BW",
    "BLACK 2 / WHITE 2": "B2W2",
}
# gist label word -> the mode word used in file names ("HGSS Super Kaizo.rnqs")
MODES = {
    "standard": "Standard", "ultimate": "Ultimate", "kaizo": "Kaizo",
    "super kaizo": "Super Kaizo", "survival": "Survival", "doubles": "Kaizo Doubles",
}
B64 = re.compile(r"^[A-Za-z0-9+/=]{40,}$")


def main():
    text = SRC.read_text(encoding="utf-8")
    rows = []
    game = None
    section = None
    in_block = False
    pending_labels = []
    for line in text.splitlines():
        s = line.strip()
        m = re.match(r"^## (.+)$", s)
        if m:
            game = GAMES.get(m.group(1).strip())
            section = None
            continue
        m = re.match(r"^#### (.+)$", s)
        if m:
            section = m.group(1).strip()
            continue
        if s.startswith("```"):
            in_block = not in_block
            pending_labels = []
            continue
        if not in_block or game is None or not (section or "").startswith("Settings Strings"):
            continue
        if "4.4.0" in (section or ""):
            continue                                      # older randomizer's strings
        if B64.match(s):
            if not pending_labels:
                continue                                  # a string with no label: not ours to guess
            for lab in pending_labels:
                rows.append((game, lab, s, section))
            pending_labels = []
            continue
        if s and not s.startswith("-"):
            # "Standard / Ultimate / Kaizo", "Survival", "PART 1:", "Doubles"
            if s.upper().startswith("PART"):
                part = s.rstrip(":").upper()
                pending_labels = [part]                   # Gen 1 two-part strings
                continue
            labels = [w.strip().lower() for w in s.split("/")]
            mapped = [MODES[w] for w in labels if w in MODES]
            if mapped:
                pending_labels = mapped

    with OUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# GENERATED by tools/upr-settings/parse_gist.py from official-settings.md.\n")
        f.write("# tag\tmode\tflag\tstring\tsection\n")
        for game, mode, s, section in rows:
            flag = "TWO_PART" if game == "RBY" else "OK"
            f.write("\t".join((game, mode, flag, s, section)) + "\n")

    by = {}
    for game, mode, s, section in rows:
        by.setdefault(game, []).append(mode)
    for g in GAMES.values():
        print("%-5s %s" % (g, ", ".join(by.get(g, [])) or "(none found)"))
    print("%d rows -> %s" % (len(rows), OUT.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
