package com.ironmonone.tracker

// GENERATED by tools/hns/gen_tracker.py from app/src/main/assets/hns/layout-kaizo.json. Do not hand-edit:
// rebuild the layout (tools/hns/layout.py) and run the generator again.

/** The Heart & Soul Kaizo comfort build's layout (CRC E35A0E40): every address, struct field and constant the
 *  tracker reads, exactly as the build's own symbols and compiled structs give them. */
@Suppress("ObjectPropertyName", "PropertyName", "unused", "SpellCheckingInspection")
internal object HnsLayout {
    const val BUILD_CRC = 0xE35A0E40L

    // Symbols (ELF st_value: a code address carries its thumb bit, as gBattleMainFunc holds it).
    const val CB2_EndScriptedWildBattle = 0x080B63A9L
    const val CB2_EndWildBattle = 0x080B61ADL
    const val CB2_Overworld = 0x0819A659L
    const val CB2_OverworldBasic = 0x0819A881L
    const val DoBattleIntro = 0x08087E4DL
    const val HandleTurnActionSelectionState = 0x08088F15L
    const val ReturnFromBattleToOverworld = 0x08083935L
    const val TryDoEventsBeforeFirstTurn = 0x08085045L
    const val gAbilitiesInfo = 0x08D35554L
    const val gActionsByTurnOrder = 0x02000300L
    const val gBattleCommunication = 0x020001B8L
    const val gBattleEnvironment = 0x02000307L
    const val gBattleMainFunc = 0x03002F74L
    const val gBattleMons = 0x0200041CL
    const val gBattleOutcome = 0x02000230L
    const val gBattlePartners = 0x0847DFA8L
    const val gBattleResults = 0x03002F80L
    const val gBattleScripting = 0x020000E8L
    const val gBattleStruct = 0x020000B4L
    const val gBattleTextBuff1 = 0x02000128L
    const val gBattleTurnCounter = 0x02000304L
    const val gBattleTypeFlags = 0x020000ACL
    const val gBattleWeather = 0x0200038CL
    const val gBattlerAbility = 0x020002FAL
    const val gBattlerAttacker = 0x02000124L
    const val gBattlerPartyIndexes = 0x0200013CL
    const val gBattlerPositions = 0x02000234L
    const val gBattlerTarget = 0x0200038AL
    const val gBattlersCount = 0x020000B0L
    const val gBattlescriptCurrInstr = 0x02000144L
    const val gChosenMoveByBattler = 0x020002D8L
    const val gCurrentMove = 0x0200039CL
    const val gCurrentTurnActionNumber = 0x020002FEL
    const val gEggMonTable = 0x08D4BE88L
    const val gEnemyParty = 0x02034534L
    const val gEnemyPartyCount = 0x02034525L
    const val gExperienceTables = 0x088B795CL
    const val gFieldStatuses = 0x020002E4L
    const val gFieldTimers = 0x02000310L
    const val gFollowerSteps = 0x02034530L
    const val gHitMarker = 0x020002D4L
    const val gHnsChallengePreset = 0x087A7714L
    const val gHnsLabTrashItem = 0x087A7808L
    const val gHnsNamedGiftSpecies = 0x087A780CL
    const val gHnsRoamerSpecies = 0x087A7814L
    const val gItemsInfo = 0x0878EDE0L
    const val gLastUsedMove = 0x02000384L
    const val gMain = 0x03005BD8L
    const val gMapGroups = 0x092CC690L
    const val gMapHeader = 0x02001D08L
    const val gMovesInfo = 0x087B5B90L
    const val gNaturesInfo = 0x08D32EE0L
    const val gObjectEvents = 0x020017F0L
    const val gPaydayMoney = 0x02000390L
    const val gPlayerAvatar = 0x020017C0L
    const val gPlayerParty = 0x020349E4L
    const val gPlayerPartyCount = 0x02034524L
    const val gPlttBufferFaded = 0x02033C78L
    const val gPlttBufferUnfaded = 0x02034078L
    const val gPokemonStoragePtr = 0x030041DCL
    const val gProtectStructs = 0x020000B8L
    const val gRegionMapEntries = 0x08D5596CL
    const val gRngValue = 0x03006080L
    const val gSaveBlock1Ptr = 0x030041D8L
    const val gSaveBlock2Ptr = 0x030041D4L
    const val gSaveBlock3Ptr = 0x03000178L
    const val gSideStatuses = 0x02000320L
    const val gSideTimers = 0x02000254L
    const val gSpecialVar_ItemId = 0x02006E28L
    const val gSpecialVar_Result = 0x02001766L
    const val gSpeciesInfo = 0x087E6368L
    const val gSpriteCoordOffsetX = 0x0203A53EL
    const val gSpriteCoordOffsetY = 0x0203A540L
    const val gSprites = 0x0203A9C4L
    const val gStarterAndGiftMonTable = 0x08D4BE8CL
    const val gTMHMItemMoveIds = 0x0878EC4CL
    const val gTasks = 0x03006140L
    const val gTrainerBattleParameter = 0x0200084CL
    const val gTrainerClasses = 0x08474D34L
    const val gTrainers = 0x084C1608L
    const val gTypeEffectivenessTable = 0x08475B3CL
    const val gTypesInfo = 0x084757F4L
    const val gWildMonHeaders = 0x0918533CL
    const val sIngameTrades = 0x0912F67CL
    const val sMonSummaryScreen = 0x02034CD0L
    const val sObtainableToNationalOrder = 0x08D34308L
    const val sOddEggSpecies = 0x08D5D814L
    const val sPickupTable = 0x08481374L
    const val sStarterMon = 0x08D69230L
    const val sSubstructOffsets = 0x087E5AF0L

    // Table record counts (the symbol's size over its element's).
    const val gAbilitiesInfo_COUNT = 311
    const val gBattleMons_COUNT = 4
    const val gBattlePartners_COUNT = 21
    const val gEggMonTable_COUNT = 2
    const val gEnemyParty_COUNT = 6
    const val gExperienceTables_COUNT = 808
    const val gHnsChallengePreset_COUNT = 242
    const val gHnsLabTrashItem_COUNT = 1
    const val gHnsNamedGiftSpecies_COUNT = 4
    const val gHnsRoamerSpecies_COUNT = 4
    const val gItemsInfo_COUNT = 901
    const val gMovesInfo_COUNT = 935
    const val gPlayerParty_COUNT = 6
    const val gSpeciesInfo_COUNT = 1574
    const val gStarterAndGiftMonTable_COUNT = 11
    const val gTMHMItemMoveIds_COUNT = 101
    const val gTrainerClasses_COUNT = 172
    const val gTrainers_COUNT = 1959
    const val gTypeEffectivenessTable_COUNT = 441
    const val gTypesInfo_COUNT = 21
    const val gWildMonHeaders_COUNT = 168
    const val sIngameTrades_COUNT = 25
    const val sObtainableToNationalOrder_COUNT = 966
    const val sOddEggSpecies_COUNT = 12
    const val sPickupTable_COUNT = 30
    const val sStarterMon_COUNT = 3
    const val sSubstructOffsets_COUNT = 96

    // Battle script labels, [addr, end): end is the next symbol's address.
    val BattleScript_AbilityPopUp = 0x0829186DL until 0x0829188AL
    val BattleScript_AbilityPopUpOverwriteThenNormal = 0x08291899L until 0x082918C9L
    val BattleScript_AbilityPopUpScripting = 0x0829188AL until 0x08291899L
    val BattleScript_AbilityPopUpTarget = 0x08291863L until 0x0829186DL
    val BattleScript_BattlerDefrosted = 0x082914DDL until 0x082914E8L
    val BattleScript_FocusPunchSetUp = 0x082910D8L until 0x082910F6L
    val BattleScript_MoveUsedIsConfused = 0x082915C1L until 0x082915D9L
    val BattleScript_MoveUsedIsConfusedNoMore = 0x0829162CL until 0x08291633L
    val BattleScript_MoveUsedIsConfusedRet = 0x082915FFL until 0x08291600L
    val BattleScript_MoveUsedIsFrozen = 0x082914CBL until 0x082914DDL
    val BattleScript_MoveUsedIsInLove = 0x0829165BL until 0x08291669L
    val BattleScript_MoveUsedIsInLoveCantAttack = 0x08291669L until 0x08291674L
    val BattleScript_MoveUsedWokeUp = 0x0829145BL until 0x08291466L
    val BattleScript_SnatchedMove = 0x082910A4L until 0x082910B4L

    // Scalar constants.
    const val ABILITIES_COUNT = 311
    const val ABILITY_NAME_LENGTH = 16
    const val ACTIONS_CONFIRMED_COUNT = 4
    const val BAG_BERRIES_COUNT = 66
    const val BAG_ITEMS_COUNT = 236
    const val BAG_KEYITEMS_COUNT = 60
    const val BAG_MEDICINE_COUNT = 92
    const val BAG_POKEBALLS_COUNT = 39
    const val BAG_TMHM_COUNT = 160
    const val BG_EVENT_HIDDEN_ITEM = 7
    const val B_ACTION_USE_MOVE = 0
    const val B_PHYSICAL_SPECIAL_SPLIT = 8
    const val B_WEATHER_FOG = 256
    const val B_WEATHER_HAIL = 64
    const val B_WEATHER_RAIN = 7
    const val B_WEATHER_RAIN_PRIMAL = 2
    const val B_WEATHER_SANDSTORM = 32
    const val B_WEATHER_SNOW = 128
    const val B_WEATHER_STRONG_WINDS = 512
    const val B_WEATHER_SUN = 24
    const val B_WEATHER_SUN_PRIMAL = 16
    const val CONDITIONS_END = 39
    const val DIFFICULTY_COUNT = 3
    const val DIFFICULTY_NORMAL = 1
    const val EGG_MON_COUNT = 2
    const val EVOLUTIONS_END = 65535
    const val FISH_WILD_COUNT = 10
    const val FLAGS_COUNT = 2432
    const val FLAG_HIDDEN_ITEMS_START = 234
    const val FLAG_HNS_LAB_TRASH_ITEM_TAKEN = 775
    const val FLAG_SYS_SAFARI_MODE = 2144
    const val FORM_SPECIES_END = 65535
    const val GAME_STAT_FISHING_ENCOUNTERS = 12
    const val GAME_STAT_RESTED_AT_HOME = 16
    const val GAME_STAT_STEPS = 5
    const val GAME_STAT_USED_POKECENTER = 15
    const val GAME_STAT_USED_ROCK_SMASH = 19
    const val GEN_LATEST = 8
    const val HIDDEN_WILD_COUNT = 3
    const val HNS_CHALLENGE_ROWS = 120
    const val HNS_PRESET_LOCKS = 122
    const val HNS_PRESET_MODE = 0
    const val HNS_PRESET_MODE_KAIZO = 1
    const val HNS_PRESET_MODE_NONE = 0
    const val HNS_PRESET_MODE_NUZLOCKE = 2
    const val HNS_PRESET_SIZE = 242
    const val HNS_PRESET_SKIP_MENU = 1
    const val HNS_PRESET_VALUES = 2
    const val IN_BOX_COUNT = 30
    const val ITEM3_BURN = 8
    const val ITEM3_CONFUSION = 1
    const val ITEM3_FREEZE = 4
    const val ITEM3_PARALYSIS = 2
    const val ITEM3_POISON = 16
    const val ITEM3_SLEEP = 32
    const val ITEM3_STATUS_ALL = 63
    const val ITEM4_EVO_STONE = 128
    const val ITEM4_HEAL_HP = 4
    const val ITEM4_HEAL_PP = 8
    const val ITEM4_HEAL_PP_ONE = 16
    const val ITEM4_REVIVE = 64
    const val ITEM6_HEAL_HP_FULL = 255
    const val ITEM6_HEAL_HP_HALF = 254
    const val ITEM6_HEAL_HP_LVL_UP = 253
    const val ITEM6_HEAL_HP_QUARTER = 252
    const val ITEMS_COUNT = 901
    const val ITEM_NAME_LENGTH = 20
    const val I_COMBINE_BAG_POCKETS = 1
    const val LAND_WILD_COUNT = 12
    const val LEVEL_UP_MOVE_END = 65535
    const val MAPSEC_NONE = 125
    const val MAP_GROUPS_COUNT = 106
    const val MAP_TYPE_INDOOR = 8
    const val MAX_BATTLERS_COUNT = 4
    const val MAX_LEVEL = 100
    const val MAX_MON_MOVES = 4
    const val MAX_SPRITES = 64
    const val MAX_TRAINERS_COUNT = 864
    const val MAX_TRAINER_ITEMS = 4
    const val MON_FEMALE = 254
    const val MON_GENDERLESS = 255
    const val MON_MALE = 0
    const val MON_RANDOMIZER_INVALID = 3
    const val MOVES_COUNT = 848
    const val MOVES_COUNT_ALL = 935
    const val MOVE_NAME_LENGTH = 16
    const val MOVE_UNAVAILABLE = 65535
    const val NATIONAL_DEX_COUNT = 1080
    const val NATIONAL_DEX_DEOXYS = 386
    const val NATIONAL_DEX_NONE = 0
    const val NUMBER_OF_MON_TYPES = 21
    const val NUM_ABILITY_SLOTS = 3
    const val NUM_ALL_MACHINES = 100
    const val NUM_BADGES = 16
    const val NUM_BATTLE_STATS = 8
    const val NUM_FLAG_BYTES = 304
    const val NUM_HIDDEN_MACHINES = 8
    const val NUM_NATURES = 25
    const val NUM_SPECIES = 1573
    const val NUM_STATS = 6
    const val NUM_TECHNICAL_MACHINES = 92
    const val OBJECT_EVENTS_COUNT = 16
    const val OBTAINABLE_DEX_COUNT = 483
    const val OW_POKEMON_OBJECT_EVENTS = 1
    const val OW_TIMES_OF_DAY = 8
    const val OW_TIME_OF_DAY_DISABLE_FALLBACK = 0
    const val OW_TIME_OF_DAY_ENCOUNTERS = 1
    const val OW_TIME_OF_DAY_FALLBACK = 1
    const val PARTNER_COUNT = 7
    const val PARTY_SIZE = 6
    const val PC_ITEMS_COUNT = 50
    const val PLAYER_NAME_LENGTH = 7
    const val POKEMON_NAME_LENGTH = 12
    const val P_FOOTPRINTS = 1
    const val P_GENDER_DIFFERENCES = 1
    const val P_SEPARATE_REGIONAL_FORMS = 1
    const val RANDOMIZER_MAX_EVO_STAGES = 5
    const val RANDOMIZER_SPECIES_COUNT = 1573
    const val ROCK_WILD_COUNT = 5
    const val SEPARATE_OBTAINABLE_DEX = 1
    const val SHINY_ODDS = 8
    const val SPECIES_EGG = 1573
    const val STARTER_AND_GIFT_MON_COUNT = 11
    const val STATUS1_BURN = 16
    const val STATUS1_FREEZE = 32
    const val STATUS1_FROSTBITE = 4096
    const val STATUS1_PARALYSIS = 64
    const val STATUS1_POISON = 8
    const val STATUS1_SLEEP = 7
    const val STATUS1_TOXIC_POISON = 128
    const val SYS_FLAGS = 2144
    const val TIMES_OF_DAY_COUNT = 4
    const val TOTAL_BOXES_COUNT = 14
    const val TRAINERS_COUNT = 653
    const val TRAINER_FLAGS_START = 1280
    const val TRAINER_ID_LENGTH = 4
    const val TRAINER_NAME_LENGTH = 10
    const val TYPE_NAME_LENGTH = 8
    const val VARS_COUNT = 256
    const val VARS_START = 16384
    const val VAR_REPEL_STEP_COUNT = 16417
    const val VAR_STARTER_MON = 16419
    const val VAR_TEMP_2 = 16386
    const val WATER_WILD_COUNT = 5

    // Types (TYPE_NONE is 0, so every type is one above Gen 3's own id, Fairy 19).
    const val TYPE_NONE = 0
    const val TYPE_NORMAL = 1
    const val TYPE_FIGHTING = 2
    const val TYPE_FLYING = 3
    const val TYPE_POISON = 4
    const val TYPE_GROUND = 5
    const val TYPE_ROCK = 6
    const val TYPE_BUG = 7
    const val TYPE_GHOST = 8
    const val TYPE_STEEL = 9
    const val TYPE_MYSTERY = 10
    const val TYPE_FIRE = 11
    const val TYPE_WATER = 12
    const val TYPE_GRASS = 13
    const val TYPE_ELECTRIC = 14
    const val TYPE_PSYCHIC = 15
    const val TYPE_ICE = 16
    const val TYPE_DRAGON = 17
    const val TYPE_DARK = 18
    const val TYPE_FAIRY = 19
    const val TYPE_STELLAR = 20
    const val FLAG_BADGE01_GET = 2176
    const val FLAG_BADGE02_GET = 2177
    const val FLAG_BADGE03_GET = 2178
    const val FLAG_BADGE04_GET = 2179
    const val FLAG_BADGE05_GET = 2180
    const val FLAG_BADGE06_GET = 2181
    const val FLAG_BADGE07_GET = 2182
    const val FLAG_BADGE08_GET = 2183
    const val FLAG_BADGE09_GET = 2184
    const val FLAG_BADGE10_GET = 2185
    const val FLAG_BADGE11_GET = 2186
    const val FLAG_BADGE12_GET = 2187
    const val FLAG_BADGE13_GET = 2188
    const val FLAG_BADGE14_GET = 2189
    const val FLAG_BADGE15_GET = 2190
    const val FLAG_BADGE16_GET = 2191
    const val SPECIES_SHEDINJA = 292
    const val SPECIES_UNOWN = 201
    const val ITEM_OLD_ROD = 709
    const val ITEM_GOOD_ROD = 710
    const val ITEM_SUPER_ROD = 711
    const val ITEM_X_SP_DEF = 124
    const val ITEM_GUARD_SPEC = 128
    const val ITEM_DIRE_HIT = 127
    const val EVO_LEVEL = 1
    const val EVO_TRADE = 2
    const val EVO_ITEM = 3
    const val IF_MIN_FRIENDSHIP = 3
    const val IF_GENDER = 0
    const val IF_HOLD_ITEM = 7
    const val MON_FEMALE_GENDER = 254
    const val SIDE_STATUS_REFLECT = 1
    const val SIDE_STATUS_LIGHTSCREEN = 2
    const val SIDE_STATUS_SAFEGUARD = 4
    const val SIDE_STATUS_MIST = 8
    const val SIDE_STATUS_TAILWIND = 16
    const val SIDE_STATUS_AURORA_VEIL = 32
    const val SIDE_STATUS_SCREEN_ANY = 35
    const val SIDE_STATUS_GOOD_FOG = 47
    const val SIDE_STATUS_LUCKY_CHANT = 64
    const val SIDE_STATUS_DAMAGE_NON_TYPES = 128
    const val SIDE_STATUS_RAINBOW = 256
    const val SIDE_STATUS_GOOD_COURT = 383
    const val SIDE_STATUS_SEA_OF_FIRE = 512
    const val SIDE_STATUS_SWAMP = 1024
    const val SIDE_STATUS_BAD_COURT = 1664
    const val SIDE_STATUS_PLEDGE_ANY = 1792
    const val STATUS_FIELD_MAGIC_ROOM = 1
    const val STATUS_FIELD_TRICK_ROOM = 2
    const val STATUS_FIELD_WONDER_ROOM = 4
    const val STATUS_FIELD_MUDSPORT = 8
    const val STATUS_FIELD_WATERSPORT = 16
    const val STATUS_FIELD_GRAVITY = 32
    const val STATUS_FIELD_GRASSY_TERRAIN = 64
    const val STATUS_FIELD_MISTY_TERRAIN = 128
    const val STATUS_FIELD_ELECTRIC_TERRAIN = 256
    const val STATUS_FIELD_PSYCHIC_TERRAIN = 512
    const val STATUS_FIELD_TERRAIN_ANY = 960
    const val STATUS_FIELD_ION_DELUGE = 1024
    const val STATUS_FIELD_FAIRY_LOCK = 2048
    const val BATTLE_ENVIRONMENT_GRASS = 0
    const val BATTLE_ENVIRONMENT_LONG_GRASS = 1
    const val BATTLE_ENVIRONMENT_SAND = 2
    const val BATTLE_ENVIRONMENT_UNDERWATER = 3
    const val BATTLE_ENVIRONMENT_WATER = 4
    const val BATTLE_ENVIRONMENT_POND = 5
    const val BATTLE_ENVIRONMENT_MOUNTAIN = 6
    const val BATTLE_ENVIRONMENT_CAVE = 7
    const val BATTLE_ENVIRONMENT_BUILDING = 8
    const val BATTLE_ENVIRONMENT_PLAIN = 9
    const val BATTLE_ENVIRONMENT_FRONTIER = 10
    const val BATTLE_ENVIRONMENT_GYM = 11
    const val BATTLE_ENVIRONMENT_LEADER = 12
    const val BATTLE_ENVIRONMENT_MAGMA = 13
    const val BATTLE_ENVIRONMENT_AQUA = 14
    const val BATTLE_ENVIRONMENT_SIDNEY = 15
    const val BATTLE_ENVIRONMENT_PHOEBE = 16
    const val BATTLE_ENVIRONMENT_GLACIA = 17
    const val BATTLE_ENVIRONMENT_DRAKE = 18
    const val BATTLE_ENVIRONMENT_CHAMPION = 19
    const val BATTLE_ENVIRONMENT_GROUDON = 20
    const val BATTLE_ENVIRONMENT_KYOGRE = 21
    const val BATTLE_ENVIRONMENT_RAYQUAZA = 22
    const val BATTLE_ENVIRONMENT_BLUE_BUILDING = 23
    const val BATTLE_ENVIRONMENT_GRAY_CAVE = 24
    const val BATTLE_ENVIRONMENT_CAVE_WATER = 25
    const val BATTLE_ENVIRONMENT_GRAY_CAVE_WATER = 26
    const val BATTLE_ENVIRONMENT_WILL_HNS = 27
    const val BATTLE_ENVIRONMENT_KOGA_HNS = 28
    const val BATTLE_ENVIRONMENT_BRUNO_HNS = 29
    const val BATTLE_ENVIRONMENT_KAREN_HNS = 30
    const val BATTLE_ENVIRONMENT_ROCK_SNOW = 31
    const val BATTLE_ENVIRONMENT_MOUNTAIN_SNOW = 32
    const val BATTLE_ENVIRONMENT_VOLCANO_CAVE = 33
    const val BATTLE_ENVIRONMENT_SNOW_CAVE = 34
    const val BATTLE_ENVIRONMENT_SOARING = 35
    const val BATTLE_ENVIRONMENT_SKY_PILLAR = 36
    const val BATTLE_ENVIRONMENT_BURIAL_GROUND = 37
    const val BATTLE_ENVIRONMENT_PUDDLE = 38
    const val BATTLE_ENVIRONMENT_MARSH = 39
    const val BATTLE_ENVIRONMENT_SWAMP = 40
    const val BATTLE_ENVIRONMENT_SNOW = 41
    const val BATTLE_ENVIRONMENT_ICE = 42
    const val BATTLE_ENVIRONMENT_VOLCANO = 43
    const val BATTLE_ENVIRONMENT_DISTORTION_WORLD = 44
    const val BATTLE_ENVIRONMENT_SPACE = 45
    const val BATTLE_ENVIRONMENT_ULTRA_SPACE = 46
    const val BATTLE_ENVIRONMENT_COUNT = 47

    /** HnS item id to the id the shared tables use for the same item (vanilla Gen 3, or Nat. Dex's for the newer evolution items). */
    val VANILLA_ITEM: Map<Int, Int> = mapOf(
        1 to 4,
        2 to 3,
        3 to 2,
        4 to 1,
        5 to 12,
        7 to 6,
        8 to 8,
        9 to 7,
        11 to 10,
        13 to 9,
        14 to 11,
        23 to 5,
        211 to 95,
        212 to 97,
        213 to 96,
        214 to 98,
        215 to 102,
        216 to 93,
        217 to 94,
        218 to 99,
        219 to 100,
        220 to 101,
        227 to 201,
        228 to 218,
        232 to 89,
        398 to 193,
        399 to 192,
        441 to 199,
        465 to 187,
        492 to 90,
        493 to 91,
        796 to 92
    )
    /** Evolution items EvoText names, by the HnS item id. */
    val EVO_ITEM_METHOD: Map<Int, String> = mapOf(
        211 to "FIRE",
        212 to "WATER",
        213 to "THUNDER",
        214 to "LEAF",
        215 to "ICE",
        216 to "SUN",
        217 to "MOON",
        218 to "SHINY",
        219 to "DUSK",
        220 to "DAWN",
        227 to "DRAGON_SCALE",
        228 to "UPGRADE",
        232 to "DUBIOUS_DISC",
        441 to "METAL_COAT",
        465 to "KINGS_ROCK",
        492 to "RAZOR_CLAW",
        493 to "RAZOR_FANG",
        796 to "LINKING_CORD"
    )
    /** The X items (battle items), by the HnS item id. */
    val X_ITEMS: Set<Int> = setOf(121, 122, 122, 123, 123, 124, 125, 126)
    /** Trainer classes the tracker groups, by the HnS class id. */
    val CLASS_GROUPS: Map<Int, String> = mapOf(142 to "Gym", 143 to "Gym", 130 to "Elite4", 125 to "Elite4", 155 to "Rival", 156 to "Boss")
    /** The run is won by beating one of these (Red on Mt. Silver). */
    val FINAL_TRAINERS: Set<Int> = setOf(464, 650)
    /** The Safari Zones' own areas, (mapGroup << 8) | mapNum: not the gates, entrances or the indoor rooms. */
    val SAFARI_MAP_IDS: Set<Int> = setOf(7699, 7700, 7702, 7703, 7704, 7705, 7709, 7710, 7711, 7784, 7785, 7786, 7787)
    /** Elm's lab, (mapGroup << 8) | mapNum. */
    const val LAB_MAP_ID = 256
    /** The species word each starter ball's choice script sets, the balls left to right on the table. */
    val STARTER_BALL_SPECIES: LongArray = longArrayOf(0x083AA42DL, 0x083AA488L, 0x083AA4E3L)
    /** The rival's battles, by the starter the rival took (Tracker.Data.whichRival). */
    val RIVALS: Map<Int, String> = mapOf(443 to "CHIKORITA", 444 to "CHIKORITA", 445 to "CHIKORITA", 446 to "CHIKORITA", 447 to "CHIKORITA", 448 to "CHIKORITA", 449 to "CHIKORITA", 450 to "CYNDAQUIL", 451 to "CYNDAQUIL", 452 to "CYNDAQUIL", 453 to "CYNDAQUIL", 454 to "CYNDAQUIL", 455 to "CYNDAQUIL", 456 to "CYNDAQUIL", 457 to "TOTODILE", 458 to "TOTODILE", 459 to "TOTODILE", 460 to "TOTODILE", 461 to "TOTODILE", 462 to "TOTODILE", 463 to "TOTODILE")

    // Struct sizes and fields: HnsField(offset, size, shift, width, signed, count).
    object SpeciesInfo {
        const val SIZE = 268
        val baseHP = HnsField(0, 1, 0, 8, false, 1)
        val baseAttack = HnsField(1, 1, 0, 8, false, 1)
        val baseDefense = HnsField(2, 1, 0, 8, false, 1)
        val baseSpeed = HnsField(3, 1, 0, 8, false, 1)
        val baseSpAttack = HnsField(4, 1, 0, 8, false, 1)
        val baseSpDefense = HnsField(5, 1, 0, 8, false, 1)
        val types = HnsField(6, 2, 0, 16, false, 2)
        val catchRate = HnsField(8, 1, 0, 8, false, 1)
        val forceTeraType = HnsField(9, 1, 0, 8, false, 1)
        val expYield = HnsField(10, 2, 0, 16, false, 1)
        val evYield_Attack = HnsField(12, 1, 2, 2, false, 1)
        val evYield_Defense = HnsField(12, 1, 4, 2, false, 1)
        val evYield_HP = HnsField(12, 1, 0, 2, false, 1)
        val evYield_Speed = HnsField(12, 1, 6, 2, false, 1)
        val evYield_SpAttack = HnsField(13, 1, 0, 2, false, 1)
        val evYield_SpDefense = HnsField(13, 1, 2, 2, false, 1)
        val padding2 = HnsField(13, 1, 4, 4, false, 1)
        val itemCommon = HnsField(14, 2, 0, 16, false, 1)
        val itemRare = HnsField(16, 2, 0, 16, false, 1)
        val genderRatio = HnsField(18, 1, 0, 8, false, 1)
        val eggCycles = HnsField(19, 1, 0, 8, false, 1)
        val friendship = HnsField(20, 1, 0, 8, false, 1)
        val growthRate = HnsField(21, 1, 0, 8, false, 1)
        val eggGroups = HnsField(22, 2, 0, 16, false, 2)
        val abilities = HnsField(24, 6, 0, 48, false, 3)
        val safariZoneFleeRate = HnsField(30, 1, 0, 8, false, 1)
        val categoryName = HnsField(31, 13, 0, 104, false, 13)
        val speciesName = HnsField(44, 13, 0, 104, false, 13)
        val cryId = HnsField(56, 4, 8, 16, false, 1)
        val natDexNum = HnsField(60, 2, 0, 16, false, 1)
        val height = HnsField(62, 2, 0, 16, false, 1)
        val weight = HnsField(64, 2, 0, 16, false, 1)
        val pokemonScale = HnsField(66, 2, 0, 16, false, 1)
        val pokemonOffset = HnsField(68, 2, 0, 16, false, 1)
        val trainerScale = HnsField(70, 2, 0, 16, false, 1)
        val trainerOffset = HnsField(72, 2, 0, 16, false, 1)
        val description = HnsField(76, 4, 0, 32, false, 1)
        val bodyColor = HnsField(80, 1, 0, 7, false, 1)
        val noFlip = HnsField(80, 1, 7, 1, false, 1)
        val frontAnimDelay = HnsField(81, 1, 0, 8, false, 1)
        val frontAnimId = HnsField(82, 1, 0, 8, false, 1)
        val backAnimId = HnsField(83, 1, 0, 8, false, 1)
        val frontAnimFrames = HnsField(84, 4, 0, 32, false, 1)
        val frontPic = HnsField(88, 4, 0, 32, false, 1)
        val backPic = HnsField(92, 4, 0, 32, false, 1)
        val palette = HnsField(96, 4, 0, 32, false, 1)
        val shinyPalette = HnsField(100, 4, 0, 32, false, 1)
        val shinyPaletteModern = HnsField(104, 4, 0, 32, false, 1)
        val iconSprite = HnsField(108, 4, 0, 32, false, 1)
        val frontPicFemale = HnsField(112, 4, 0, 32, false, 1)
        val backPicFemale = HnsField(116, 4, 0, 32, false, 1)
        val paletteFemale = HnsField(120, 4, 0, 32, false, 1)
        val shinyPaletteFemale = HnsField(124, 4, 0, 32, false, 1)
        val iconSpriteFemale = HnsField(128, 4, 0, 32, false, 1)
        val footprint = HnsField(132, 4, 0, 32, false, 1)
        val frontPicSize = HnsField(136, 1, 0, 8, false, 1)
        val frontPicYOffset = HnsField(137, 1, 0, 8, false, 1)
        val backPicSize = HnsField(138, 1, 0, 8, false, 1)
        val backPicYOffset = HnsField(139, 1, 0, 8, false, 1)
        val frontPicSizeFemale = HnsField(140, 1, 0, 8, false, 1)
        val backPicSizeFemale = HnsField(141, 1, 0, 8, false, 1)
        val iconPalIndex = HnsField(142, 1, 0, 3, false, 1)
        val iconPalIndexFemale = HnsField(142, 1, 3, 3, false, 1)
        val pokemonJumpType = HnsField(142, 1, 6, 2, false, 1)
        val enemyMonElevation = HnsField(143, 1, 0, 8, false, 1)
        val isMegaEvolution = HnsField(144, 1, 6, 1, false, 1)
        val isMythical = HnsField(144, 1, 2, 1, false, 1)
        val isParadox = HnsField(144, 1, 4, 1, false, 1)
        val isPrimalReversion = HnsField(144, 1, 7, 1, false, 1)
        val isRestrictedLegendary = HnsField(144, 1, 0, 1, false, 1)
        val isSubLegendary = HnsField(144, 1, 1, 1, false, 1)
        val isTotem = HnsField(144, 1, 5, 1, false, 1)
        val isUltraBeast = HnsField(144, 1, 3, 1, false, 1)
        val cannotBeTraded = HnsField(145, 1, 7, 1, false, 1)
        val isAlolanForm = HnsField(145, 1, 3, 1, false, 1)
        val isGalarianForm = HnsField(145, 1, 4, 1, false, 1)
        val isGigantamax = HnsField(145, 1, 1, 1, false, 1)
        val isHisuianForm = HnsField(145, 1, 5, 1, false, 1)
        val isPaldeanForm = HnsField(145, 1, 6, 1, false, 1)
        val isTeraForm = HnsField(145, 1, 2, 1, false, 1)
        val isUltraBurst = HnsField(145, 1, 0, 1, false, 1)
        val dexForceRequired = HnsField(146, 1, 3, 1, false, 1)
        val isFrontierBanned = HnsField(146, 1, 5, 1, false, 1)
        val isSkyBattleBanned = HnsField(146, 1, 6, 1, false, 1)
        val perfectIVCount = HnsField(146, 1, 0, 3, false, 1)
        val randomizerMode = HnsField(146, 2, 7, 2, false, 1)
        val teachingType = HnsField(146, 1, 4, 1, false, 1)
        val dexNotRequired = HnsField(147, 1, 1, 1, false, 1)
        val padding4 = HnsField(147, 1, 2, 6, false, 1)
        val enemyShadowXOffset = HnsField(148, 1, 0, 8, true, 1)
        val enemyShadowYOffset = HnsField(149, 1, 0, 8, true, 1)
        val eggId = HnsField(150, 2, 4, 12, false, 1)
        val enemyShadowSize = HnsField(150, 1, 0, 3, false, 1)
        val suppressEnemyShadow = HnsField(150, 1, 3, 1, false, 1)
        val levelUpLearnset = HnsField(152, 4, 0, 32, false, 1)
        val teachableLearnset = HnsField(156, 4, 0, 32, false, 1)
        val eggMoveLearnset = HnsField(160, 4, 0, 32, false, 1)
        val evolutions = HnsField(164, 4, 0, 32, false, 1)
        val formSpeciesIdTable = HnsField(168, 4, 0, 32, false, 1)
        val formChangeTable = HnsField(172, 4, 0, 32, false, 1)
        val overworldData = HnsField(176, 36, 0, 288, false, 1)
        val overworldDataFemale = HnsField(212, 36, 0, 288, false, 1)
        val overworldPalette = HnsField(248, 4, 0, 32, false, 1)
        val overworldShinyPalette = HnsField(252, 4, 0, 32, false, 1)
        val overworldShinyPaletteModern = HnsField(256, 4, 0, 32, false, 1)
        val overworldPaletteFemale = HnsField(260, 4, 0, 32, false, 1)
        val overworldShinyPaletteFemale = HnsField(264, 4, 0, 32, false, 1)
    }
    object MoveInfo {
        const val SIZE = 68
        val name = HnsField(0, 4, 0, 32, false, 1)
        val description = HnsField(4, 4, 0, 32, false, 1)
        val effect = HnsField(8, 2, 0, 16, false, 1)
        val category = HnsField(10, 1, 5, 2, false, 1)
        val power = HnsField(10, 2, 7, 9, false, 1)
        val type = HnsField(10, 1, 0, 5, false, 1)
        val accuracy = HnsField(12, 1, 0, 7, false, 1)
        val target = HnsField(12, 2, 7, 9, false, 1)
        val pp = HnsField(14, 1, 0, 8, false, 1)
        val zMove = HnsField(16, 4, 0, 32, false, 1)
        val priority = HnsField(20, 1, 0, 4, true, 1)
        val strikeCount = HnsField(20, 1, 4, 4, false, 1)
        val alwaysCriticalHit = HnsField(21, 1, 4, 1, false, 1)
        val criticalHitStage = HnsField(21, 1, 2, 2, false, 1)
        val explosion = HnsField(21, 1, 1, 1, false, 1)
        val multiHit = HnsField(21, 1, 0, 1, false, 1)
        val numAdditionalEffects = HnsField(21, 1, 5, 3, false, 1)
        val bitingMove = HnsField(22, 1, 6, 1, false, 1)
        val ignoresKingsRock = HnsField(22, 1, 4, 1, false, 1)
        val ignoresProtect = HnsField(22, 1, 1, 1, false, 1)
        val magicCoatAffected = HnsField(22, 1, 2, 1, false, 1)
        val makesContact = HnsField(22, 1, 0, 1, false, 1)
        val pulseMove = HnsField(22, 1, 7, 1, false, 1)
        val punchingMove = HnsField(22, 1, 5, 1, false, 1)
        val snatchAffected = HnsField(22, 1, 3, 1, false, 1)
        val ballisticMove = HnsField(23, 1, 1, 1, false, 1)
        val danceMove = HnsField(23, 1, 3, 1, false, 1)
        val healingMove = HnsField(23, 1, 6, 1, false, 1)
        val minimizeDoubleDamage = HnsField(23, 1, 7, 1, false, 1)
        val powderMove = HnsField(23, 1, 2, 1, false, 1)
        val slicingMove = HnsField(23, 1, 5, 1, false, 1)
        val soundMove = HnsField(23, 1, 0, 1, false, 1)
        val windMove = HnsField(23, 1, 4, 1, false, 1)
        val damagesAirborne = HnsField(24, 1, 4, 1, false, 1)
        val damagesAirborneDoubleDamage = HnsField(24, 1, 5, 1, false, 1)
        val damagesUnderground = HnsField(24, 1, 2, 1, false, 1)
        val damagesUnderwater = HnsField(24, 1, 3, 1, false, 1)
        val ignoreTypeIfFlyingAndUngrounded = HnsField(24, 1, 6, 1, false, 1)
        val ignoresTargetAbility = HnsField(24, 1, 0, 1, false, 1)
        val ignoresTargetDefenseEvasionStages = HnsField(24, 1, 1, 1, false, 1)
        val thawsUser = HnsField(24, 1, 7, 1, false, 1)
        val accuracy50InSun = HnsField(25, 1, 4, 1, false, 1)
        val alwaysHitsInHailSnow = HnsField(25, 1, 5, 1, false, 1)
        val alwaysHitsInRain = HnsField(25, 1, 3, 1, false, 1)
        val alwaysHitsOnSameType = HnsField(25, 1, 6, 1, false, 1)
        val cantUseTwice = HnsField(25, 1, 2, 1, false, 1)
        val forcePressure = HnsField(25, 1, 1, 1, false, 1)
        val ignoresSubstitute = HnsField(25, 1, 0, 1, false, 1)
        val noAffectOnSameTypeTarget = HnsField(25, 1, 7, 1, false, 1)
        val accIncreaseByTenOnSameType = HnsField(26, 1, 0, 1, false, 1)
        val padding1 = HnsField(26, 2, 1, 15, false, 1)
        val assistBanned = HnsField(28, 1, 6, 1, false, 1)
        val copycatBanned = HnsField(28, 1, 5, 1, false, 1)
        val gravityBanned = HnsField(28, 1, 0, 1, false, 1)
        val meFirstBanned = HnsField(28, 1, 2, 1, false, 1)
        val metronomeBanned = HnsField(28, 1, 4, 1, false, 1)
        val mimicBanned = HnsField(28, 1, 3, 1, false, 1)
        val mirrorMoveBanned = HnsField(28, 1, 1, 1, false, 1)
        val sleepTalkBanned = HnsField(28, 1, 7, 1, false, 1)
        val dampBanned = HnsField(29, 1, 5, 1, false, 1)
        val encoreBanned = HnsField(29, 1, 1, 1, false, 1)
        val instructBanned = HnsField(29, 1, 0, 1, false, 1)
        val parentalBondBanned = HnsField(29, 1, 2, 1, false, 1)
        val randomizerInvalid = HnsField(29, 1, 7, 1, false, 1)
        val sketchBanned = HnsField(29, 1, 4, 1, false, 1)
        val skyBattleBanned = HnsField(29, 1, 3, 1, false, 1)
        val validApprenticeMove = HnsField(29, 1, 6, 1, false, 1)
        val padding2 = HnsField(30, 2, 0, 16, false, 1)
        val argument = HnsField(32, 8, 0, 64, false, 1)
        val additionalEffects = HnsField(40, 4, 0, 32, false, 1)
        val contestEffect = HnsField(44, 1, 0, 8, false, 1)
        val contestCategory = HnsField(45, 1, 0, 3, false, 1)
        val contestComboStarterId = HnsField(46, 1, 0, 8, false, 1)
        val contestComboMoves = HnsField(47, 17, 0, 136, false, 17)
        val battleAnimScript = HnsField(64, 4, 0, 32, false, 1)
    }
    object AbilityInfo {
        const val SIZE = 28
        val name = HnsField(0, 17, 0, 136, false, 17)
        val description = HnsField(20, 4, 0, 32, false, 1)
        val aiRating = HnsField(24, 1, 0, 8, true, 1)
        val breakable = HnsField(25, 1, 5, 1, false, 1)
        val cantBeCopied = HnsField(25, 1, 0, 1, false, 1)
        val cantBeOverwritten = HnsField(25, 1, 4, 1, false, 1)
        val cantBeSuppressed = HnsField(25, 1, 3, 1, false, 1)
        val cantBeSwapped = HnsField(25, 1, 1, 1, false, 1)
        val cantBeTraced = HnsField(25, 1, 2, 1, false, 1)
        val failsOnImposter = HnsField(25, 1, 6, 1, false, 1)
    }
    object ItemInfo {
        const val SIZE = 44
        val price = HnsField(0, 4, 0, 32, false, 1)
        val secondaryId = HnsField(4, 2, 0, 16, false, 1)
        val fieldUseFunc = HnsField(8, 4, 0, 32, false, 1)
        val description = HnsField(12, 4, 0, 32, false, 1)
        val effect = HnsField(16, 4, 0, 32, false, 1)
        val name = HnsField(20, 4, 0, 32, false, 1)
        val pluralName = HnsField(24, 4, 0, 32, false, 1)
        val holdEffect = HnsField(28, 1, 0, 8, false, 1)
        val holdEffectParam = HnsField(29, 1, 0, 8, false, 1)
        val importance = HnsField(30, 1, 0, 2, false, 1)
        val notConsumed = HnsField(30, 1, 2, 1, false, 1)
        val pocket = HnsField(30, 1, 3, 5, false, 1)
        val sortType = HnsField(31, 1, 0, 8, false, 1)
        val type = HnsField(32, 1, 0, 8, false, 1)
        val battleUsage = HnsField(33, 1, 0, 8, false, 1)
        val flingPower = HnsField(34, 1, 0, 8, false, 1)
        val iconPic = HnsField(36, 4, 0, 32, false, 1)
        val iconPalette = HnsField(40, 4, 0, 32, false, 1)
    }
    object TypeInfo {
        const val SIZE = 40
        val name = HnsField(0, 9, 0, 72, false, 9)
        val generic = HnsField(9, 17, 0, 136, false, 17)
        val palette = HnsField(26, 1, 0, 8, false, 1)
        val zMove = HnsField(28, 2, 0, 16, false, 1)
        val maxMove = HnsField(30, 2, 0, 16, false, 1)
        val teraTypeRGBValue = HnsField(32, 2, 0, 16, false, 1)
        val damageCategory = HnsField(34, 1, 0, 2, false, 1)
        val isHiddenPowerType = HnsField(34, 1, 4, 1, false, 1)
        val isSpecialCaseType = HnsField(34, 1, 3, 1, false, 1)
        val padding = HnsField(34, 2, 5, 11, false, 1)
        val useSecondTypeIconPalette = HnsField(34, 1, 2, 1, false, 1)
        val paletteTMHM = HnsField(36, 4, 0, 32, false, 1)
    }
    object LevelUpMove {
        const val SIZE = 4
        val move = HnsField(0, 2, 0, 16, false, 1)
        val level = HnsField(2, 2, 0, 16, false, 1)
    }
    object Evolution {
        const val SIZE = 12
        val method = HnsField(0, 2, 0, 16, false, 1)
        val param = HnsField(2, 2, 0, 16, false, 1)
        val targetSpecies = HnsField(4, 2, 0, 16, false, 1)
        val params = HnsField(8, 4, 0, 32, false, 1)
    }
    object EvolutionParam {
        const val SIZE = 8
        val condition = HnsField(0, 2, 0, 16, false, 1)
        val arg1 = HnsField(2, 2, 0, 16, false, 1)
        val arg2 = HnsField(4, 2, 0, 16, false, 1)
        val arg3 = HnsField(6, 2, 0, 16, false, 1)
    }
    object BoxPokemon {
        const val SIZE = 80
        val personality = HnsField(0, 4, 0, 32, false, 1)
        val otId = HnsField(4, 4, 0, 32, false, 1)
        val nickname = HnsField(8, 10, 0, 80, false, 10)
        val hiddenNatureModifier = HnsField(18, 1, 3, 5, false, 1)
        val language = HnsField(18, 1, 0, 3, false, 1)
        val blockBoxRS = HnsField(19, 1, 3, 1, false, 1)
        val daysSinceFormChange = HnsField(19, 1, 4, 3, false, 1)
        val hasSpecies = HnsField(19, 1, 1, 1, false, 1)
        val isBadEgg = HnsField(19, 1, 0, 1, false, 1)
        val isEgg = HnsField(19, 1, 2, 1, false, 1)
        val unused_13 = HnsField(19, 1, 7, 1, false, 1)
        val otName = HnsField(20, 7, 0, 56, false, 7)
        val compressedStatus = HnsField(27, 1, 4, 4, false, 1)
        val markings = HnsField(27, 1, 0, 4, false, 1)
        val checksum = HnsField(28, 2, 0, 16, false, 1)
        val hpLost = HnsField(30, 2, 0, 14, false, 1)
        val shinyModifier = HnsField(31, 1, 6, 1, false, 1)
        val unused_1E = HnsField(31, 1, 7, 1, false, 1)
        val secure = HnsField(32, 48, 0, 384, false, 1)
    }
    object Pokemon {
        const val SIZE = 100
        val box = HnsField(0, 80, 0, 640, false, 1)
        val status = HnsField(80, 4, 0, 32, false, 1)
        val level = HnsField(84, 1, 0, 8, false, 1)
        val mail = HnsField(85, 1, 0, 8, false, 1)
        val hp = HnsField(86, 2, 0, 16, false, 1)
        val maxHP = HnsField(88, 2, 0, 16, false, 1)
        val attack = HnsField(90, 2, 0, 16, false, 1)
        val defense = HnsField(92, 2, 0, 16, false, 1)
        val speed = HnsField(94, 2, 0, 16, false, 1)
        val spAttack = HnsField(96, 2, 0, 16, false, 1)
        val spDefense = HnsField(98, 2, 0, 16, false, 1)
    }
    object PokemonSubstruct0 {
        const val SIZE = 12
        val species = HnsField(0, 2, 0, 11, false, 1)
        val teraType = HnsField(1, 1, 3, 5, false, 1)
        val heldItem = HnsField(2, 2, 0, 10, false, 1)
        val unused_02 = HnsField(3, 1, 2, 6, false, 1)
        val experience = HnsField(4, 4, 0, 21, false, 1)
        val nickname11 = HnsField(6, 2, 5, 8, false, 1)
        val unused_04 = HnsField(7, 1, 5, 3, false, 1)
        val ppBonuses = HnsField(8, 1, 0, 8, false, 1)
        val friendship = HnsField(9, 1, 0, 8, false, 1)
        val nickname12 = HnsField(10, 2, 6, 8, false, 1)
        val pokeball = HnsField(10, 1, 0, 6, false, 1)
        val unused_0A = HnsField(11, 1, 6, 2, false, 1)
    }
    object PokemonSubstruct1 {
        const val SIZE = 12
        val move1 = HnsField(0, 2, 0, 11, false, 1)
        val evolutionTracker1 = HnsField(1, 1, 3, 5, false, 1)
        val move2 = HnsField(2, 2, 0, 11, false, 1)
        val evolutionTracker2 = HnsField(3, 1, 3, 5, false, 1)
        val move3 = HnsField(4, 2, 0, 11, false, 1)
        val unused_04 = HnsField(5, 1, 3, 5, false, 1)
        val move4 = HnsField(6, 2, 0, 11, false, 1)
        val hyperTrainedAttack = HnsField(7, 1, 7, 1, false, 1)
        val hyperTrainedHP = HnsField(7, 1, 6, 1, false, 1)
        val unused_06 = HnsField(7, 1, 3, 3, false, 1)
        val hyperTrainedDefense = HnsField(8, 1, 7, 1, false, 1)
        val pp1 = HnsField(8, 1, 0, 7, false, 1)
        val hyperTrainedSpeed = HnsField(9, 1, 7, 1, false, 1)
        val pp2 = HnsField(9, 1, 0, 7, false, 1)
        val hyperTrainedSpAttack = HnsField(10, 1, 7, 1, false, 1)
        val pp3 = HnsField(10, 1, 0, 7, false, 1)
        val hyperTrainedSpDefense = HnsField(11, 1, 7, 1, false, 1)
        val pp4 = HnsField(11, 1, 0, 7, false, 1)
    }
    object PokemonSubstruct2 {
        const val SIZE = 12
        val hpEV = HnsField(0, 1, 0, 8, false, 1)
        val attackEV = HnsField(1, 1, 0, 8, false, 1)
        val defenseEV = HnsField(2, 1, 0, 8, false, 1)
        val speedEV = HnsField(3, 1, 0, 8, false, 1)
        val spAttackEV = HnsField(4, 1, 0, 8, false, 1)
        val spDefenseEV = HnsField(5, 1, 0, 8, false, 1)
        val cool = HnsField(6, 1, 0, 8, false, 1)
        val beauty = HnsField(7, 1, 0, 8, false, 1)
        val cute = HnsField(8, 1, 0, 8, false, 1)
        val smart = HnsField(9, 1, 0, 8, false, 1)
        val tough = HnsField(10, 1, 0, 8, false, 1)
        val sheen = HnsField(11, 1, 0, 8, false, 1)
    }
    object PokemonSubstruct3 {
        const val SIZE = 12
        val pokerus = HnsField(0, 1, 0, 8, false, 1)
        val metLocation = HnsField(1, 1, 0, 8, false, 1)
        val metGame = HnsField(2, 2, 7, 4, false, 1)
        val metLevel = HnsField(2, 1, 0, 7, false, 1)
        val dynamaxLevel = HnsField(3, 1, 3, 4, false, 1)
        val otGender = HnsField(3, 1, 7, 1, false, 1)
        val attackIV = HnsField(4, 2, 5, 5, false, 1)
        val hpIV = HnsField(4, 1, 0, 5, false, 1)
        val speedIV = HnsField(4, 4, 15, 5, false, 1)
        val defenseIV = HnsField(5, 1, 2, 5, false, 1)
        val spAttackIV = HnsField(6, 2, 4, 5, false, 1)
        val gigantamaxFactor = HnsField(7, 1, 7, 1, false, 1)
        val isEgg = HnsField(7, 1, 6, 1, false, 1)
        val spDefenseIV = HnsField(7, 1, 1, 5, false, 1)
        val beautyRibbon = HnsField(8, 1, 3, 3, false, 1)
        val coolRibbon = HnsField(8, 1, 0, 3, false, 1)
        val cuteRibbon = HnsField(8, 2, 6, 3, false, 1)
        val championRibbon = HnsField(9, 1, 7, 1, false, 1)
        val smartRibbon = HnsField(9, 1, 1, 3, false, 1)
        val toughRibbon = HnsField(9, 1, 4, 3, false, 1)
        val artistRibbon = HnsField(10, 1, 2, 1, false, 1)
        val countryRibbon = HnsField(10, 1, 7, 1, false, 1)
        val effortRibbon = HnsField(10, 1, 3, 1, false, 1)
        val landRibbon = HnsField(10, 1, 5, 1, false, 1)
        val marineRibbon = HnsField(10, 1, 4, 1, false, 1)
        val skyRibbon = HnsField(10, 1, 6, 1, false, 1)
        val victoryRibbon = HnsField(10, 1, 1, 1, false, 1)
        val winningRibbon = HnsField(10, 1, 0, 1, false, 1)
        val abilityNum = HnsField(11, 1, 5, 2, false, 1)
        val earthRibbon = HnsField(11, 1, 1, 1, false, 1)
        val isShadow = HnsField(11, 1, 3, 1, false, 1)
        val modernFatefulEncounter = HnsField(11, 1, 7, 1, false, 1)
        val nationalRibbon = HnsField(11, 1, 0, 1, false, 1)
        val unused_0B = HnsField(11, 1, 4, 1, false, 1)
        val worldRibbon = HnsField(11, 1, 2, 1, false, 1)
    }
    object BattlePokemon {
        const val SIZE = 136
        val species = HnsField(0, 2, 0, 16, false, 1)
        val attack = HnsField(2, 2, 0, 16, false, 1)
        val defense = HnsField(4, 2, 0, 16, false, 1)
        val speed = HnsField(6, 2, 0, 16, false, 1)
        val spAttack = HnsField(8, 2, 0, 16, false, 1)
        val spDefense = HnsField(10, 2, 0, 16, false, 1)
        val moves = HnsField(12, 8, 0, 64, false, 4)
        val attackIV = HnsField(20, 2, 5, 5, false, 1)
        val hpIV = HnsField(20, 1, 0, 5, false, 1)
        val speedIV = HnsField(20, 4, 15, 5, false, 1)
        val defenseIV = HnsField(21, 1, 2, 5, false, 1)
        val spAttackIV = HnsField(22, 2, 4, 5, false, 1)
        val abilityNum = HnsField(23, 1, 6, 2, false, 1)
        val spDefenseIV = HnsField(23, 1, 1, 5, false, 1)
        val statStages = HnsField(24, 8, 0, 64, true, 8)
        val ability = HnsField(32, 2, 0, 16, false, 1)
        val types = HnsField(34, 3, 0, 24, false, 3)
        val pp = HnsField(37, 4, 0, 32, false, 4)
        val hp = HnsField(42, 2, 0, 16, false, 1)
        val level = HnsField(44, 1, 0, 8, false, 1)
        val friendship = HnsField(45, 1, 0, 8, false, 1)
        val maxHP = HnsField(46, 2, 0, 16, false, 1)
        val item = HnsField(48, 2, 0, 16, false, 1)
        val nickname = HnsField(50, 13, 0, 104, false, 13)
        val ppBonuses = HnsField(63, 1, 0, 8, false, 1)
        val otName = HnsField(64, 8, 0, 64, false, 8)
        val experience = HnsField(72, 4, 0, 32, false, 1)
        val personality = HnsField(76, 4, 0, 32, false, 1)
        val status1 = HnsField(80, 4, 0, 32, false, 1)
        val volatiles = HnsField(84, 44, 0, 352, false, 1)
        val otId = HnsField(128, 4, 0, 32, false, 1)
        val metLevel = HnsField(132, 1, 0, 8, false, 1)
        val isShiny = HnsField(133, 1, 0, 8, false, 1)
    }
    object Volatiles {
        const val SIZE = 44
        val confusionTurns = HnsField(0, 1, 0, 3, false, 1)
        val flinched = HnsField(0, 1, 3, 1, false, 1)
        val torment = HnsField(0, 1, 7, 1, false, 1)
        val uproarTurns = HnsField(0, 1, 4, 3, false, 1)
        val bideTurns = HnsField(1, 1, 0, 2, false, 1)
        val multipleTurns = HnsField(1, 1, 5, 1, false, 1)
        val rampageTurns = HnsField(1, 1, 2, 3, false, 1)
        val wrapped = HnsField(1, 1, 6, 1, false, 1)
        val wrappedBy = HnsField(2, 1, 0, 4, false, 1)
        val wrappedMove = HnsField(2, 2, 4, 10, false, 1)
        val padding = HnsField(3, 1, 7, 1, false, 1)
        val powder = HnsField(3, 1, 6, 1, false, 1)
        val defenseCurl = HnsField(4, 1, 4, 1, false, 1)
        val infatuation = HnsField(4, 1, 0, 4, false, 1)
        val rage = HnsField(4, 1, 6, 1, false, 1)
        val substitute = HnsField(4, 1, 7, 1, false, 1)
        val transformed = HnsField(4, 1, 5, 1, false, 1)
        val cursed = HnsField(5, 1, 4, 1, false, 1)
        val destinyBond = HnsField(5, 1, 0, 2, false, 1)
        val dragonCheer = HnsField(5, 1, 6, 1, false, 1)
        val escapePrevention = HnsField(5, 1, 2, 1, false, 1)
        val focusEnergy = HnsField(5, 1, 7, 1, false, 1)
        val foresight = HnsField(5, 1, 5, 1, false, 1)
        val nightmare = HnsField(5, 1, 3, 1, false, 1)
        val bonusCritStages = HnsField(6, 1, 0, 3, false, 1)
        val electrified = HnsField(6, 1, 6, 1, false, 1)
        val mudSport = HnsField(6, 1, 7, 1, false, 1)
        val semiInvulnerable = HnsField(6, 1, 3, 3, false, 1)
        val infiniteConfusion = HnsField(7, 1, 1, 1, false, 1)
        val saltCure = HnsField(7, 1, 2, 1, false, 1)
        val stickySyrupedBy = HnsField(7, 1, 4, 4, false, 1)
        val syrupBomb = HnsField(7, 1, 3, 1, false, 1)
        val waterSport = HnsField(7, 1, 0, 1, false, 1)
        val glaiveRush = HnsField(8, 1, 0, 1, false, 1)
        val leechSeed = HnsField(8, 1, 1, 4, false, 1)
        val lockOn = HnsField(8, 1, 5, 2, false, 1)
        val perishSong = HnsField(8, 1, 7, 1, false, 1)
        val chargeTimer = HnsField(9, 1, 1, 2, false, 1)
        val grudge = HnsField(9, 1, 7, 1, false, 1)
        val imprison = HnsField(9, 1, 6, 1, false, 1)
        val minimize = HnsField(9, 1, 0, 1, false, 1)
        val root = HnsField(9, 1, 3, 1, false, 1)
        val yawn = HnsField(9, 1, 4, 2, false, 1)
        val aquaRing = HnsField(10, 1, 7, 1, false, 1)
        val embargo = HnsField(10, 1, 1, 1, false, 1)
        val gastroAcid = HnsField(10, 1, 0, 1, false, 1)
        val healBlock = HnsField(10, 1, 6, 1, false, 1)
        val magnetRise = HnsField(10, 1, 5, 1, false, 1)
        val miracleEye = HnsField(10, 1, 4, 1, false, 1)
        val smackDown = HnsField(10, 1, 2, 1, false, 1)
        val telekinesis = HnsField(10, 1, 3, 1, false, 1)
        val beadsOfRuin = HnsField(11, 1, 6, 1, false, 1)
        val isTransformedMonShiny = HnsField(11, 1, 7, 1, false, 1)
        val laserFocus = HnsField(11, 1, 0, 1, false, 1)
        val noRetreat = HnsField(11, 1, 2, 1, false, 1)
        val powerTrick = HnsField(11, 1, 1, 1, false, 1)
        val swordOfRuin = HnsField(11, 1, 4, 1, false, 1)
        val tabletsOfRuin = HnsField(11, 1, 5, 1, false, 1)
        val vesselOfRuin = HnsField(11, 1, 3, 1, false, 1)
        val transformedMonPID = HnsField(12, 4, 0, 32, false, 1)
        val disabledMove = HnsField(16, 4, 11, 10, false, 1)
        val transformedMonSpecies = HnsField(16, 2, 0, 11, false, 1)
        val encoredMove = HnsField(18, 2, 5, 10, false, 1)
        val consecutiveMoveUses = HnsField(20, 1, 0, 8, false, 1)
        val stockpileCounter = HnsField(21, 1, 0, 4, false, 1)
        val stockpileDef = HnsField(21, 1, 4, 4, false, 1)
        val stockpileBeforeDef = HnsField(22, 1, 4, 4, false, 1)
        val stockpileSpDef = HnsField(22, 1, 0, 4, false, 1)
        val stockpileBeforeSpDef = HnsField(23, 1, 0, 4, false, 1)
        val encoreTimer = HnsField(24, 4, 15, 3, false, 1)
        val substituteHP = HnsField(24, 1, 0, 8, false, 1)
        val disableTimer = HnsField(25, 1, 4, 3, false, 1)
        val encoredMovePos = HnsField(25, 1, 0, 4, false, 1)
        val perishSongTimer = HnsField(26, 1, 2, 2, false, 1)
        val rolloutTimer = HnsField(26, 2, 4, 8, false, 1)
        val furyCutterCounter = HnsField(28, 1, 0, 8, false, 1)
        val metronomeItemCounter = HnsField(29, 1, 0, 8, false, 1)
        val battlerPreventingEscape = HnsField(30, 1, 0, 4, false, 1)
        val battlerWithSureHit = HnsField(30, 1, 4, 3, false, 1)
        val mimickedMoves = HnsField(30, 2, 7, 4, false, 1)
        val rechargeTimer = HnsField(31, 1, 3, 2, false, 1)
        val autotomizeCount = HnsField(32, 1, 0, 8, false, 1)
        val magnetRiseTimer = HnsField(32, 4, 14, 3, false, 1)
        val embargoTimer = HnsField(33, 1, 3, 3, false, 1)
        val slowStartTimer = HnsField(33, 1, 0, 3, false, 1)
        val healBlockTimer = HnsField(34, 1, 3, 3, false, 1)
        val tauntTimer = HnsField(34, 2, 6, 3, false, 1)
        val telekinesisTimer = HnsField(34, 1, 1, 2, false, 1)
        val laserFocusTimer = HnsField(35, 1, 3, 2, false, 1)
        val throatChopTimer = HnsField(35, 1, 5, 2, false, 1)
        val tormentTimer = HnsField(35, 1, 1, 2, false, 1)
        val syrupBombTimer = HnsField(36, 1, 3, 2, false, 1)
        val usedMoves = HnsField(36, 2, 5, 4, false, 1)
        val wrapTurns = HnsField(36, 1, 0, 3, false, 1)
        val cudChew = HnsField(37, 1, 5, 1, false, 1)
        val octolock = HnsField(37, 1, 4, 1, false, 1)
        val tarShot = HnsField(37, 1, 3, 1, false, 1)
        val terrainAbilityDone = HnsField(37, 1, 7, 1, false, 1)
        val truantCounter = HnsField(37, 1, 1, 1, false, 1)
        val truantSwitchInHack = HnsField(37, 1, 2, 1, false, 1)
        val weatherAbilityDone = HnsField(37, 1, 6, 1, false, 1)
        val boosterEnergyActivated = HnsField(38, 1, 4, 1, false, 1)
        val embodyAspectActivated = HnsField(38, 1, 2, 1, false, 1)
        val flashFireBoosted = HnsField(38, 1, 3, 1, false, 1)
        val overwrittenAbility = HnsField(38, 2, 5, 9, false, 1)
        val syrupBombIsShiny = HnsField(38, 1, 0, 1, false, 1)
        val usedProteanLibero = HnsField(38, 1, 1, 1, false, 1)
        val roostActive = HnsField(39, 1, 6, 1, false, 1)
        val unburdenActive = HnsField(39, 1, 7, 1, false, 1)
        val endured = HnsField(40, 1, 2, 1, false, 1)
        val neutralizingGas = HnsField(40, 1, 0, 1, false, 1)
        val octolockedBy = HnsField(40, 1, 4, 4, false, 1)
        val tryEjectPack = HnsField(40, 1, 3, 1, false, 1)
        val unnerveActivated = HnsField(40, 1, 1, 1, false, 1)
        val activateDancer = HnsField(41, 1, 4, 1, false, 1)
        val paradoxBoostedStat = HnsField(41, 1, 0, 3, false, 1)
        val unableToUseMove = HnsField(41, 1, 3, 1, false, 1)
    }
    object Bag {
        const val SIZE = 2612
        val items = HnsField(0, 944, 0, 7552, false, 236)
        val keyItems = HnsField(944, 240, 0, 1920, false, 60)
        val pokeBalls = HnsField(1184, 156, 0, 1248, false, 39)
        val TMsHMs = HnsField(1340, 640, 0, 5120, false, 160)
        val berries = HnsField(1980, 264, 0, 2112, false, 66)
        val medicine = HnsField(2244, 368, 0, 2944, false, 92)
    }
    object ItemSlot {
        const val SIZE = 4
        val itemId = HnsField(0, 2, 0, 16, false, 1)
        val quantity = HnsField(2, 2, 0, 16, false, 1)
    }
    object Trainer {
        const val SIZE = 52
        val aiFlags = HnsField(0, 8, 0, 64, false, 1)
        val party = HnsField(8, 4, 0, 32, false, 1)
        val items = HnsField(12, 8, 0, 64, false, 4)
        val startingStatus = HnsField(20, 8, 0, 64, false, 1)
        val trainerClass = HnsField(28, 1, 0, 8, false, 1)
        val encounterMusic = HnsField(29, 1, 0, 7, false, 1)
        val gender = HnsField(29, 1, 7, 1, false, 1)
        val trainerPic = HnsField(30, 1, 0, 8, false, 1)
        val trainerName = HnsField(31, 11, 0, 88, false, 11)
        val battleType = HnsField(42, 1, 0, 2, false, 1)
        val mugshotColor = HnsField(42, 1, 2, 6, false, 1)
        val partySize = HnsField(43, 1, 0, 8, false, 1)
        val poolSize = HnsField(44, 1, 0, 8, false, 1)
        val poolRuleIndex = HnsField(45, 1, 0, 8, false, 1)
        val poolPickIndex = HnsField(46, 1, 0, 8, false, 1)
        val poolPruneIndex = HnsField(47, 1, 0, 8, false, 1)
        val overrideTrainer = HnsField(48, 2, 0, 16, false, 1)
        val trainerBackPic = HnsField(50, 1, 0, 8, false, 1)
    }
    object TrainerMon {
        const val SIZE = 36
        val nickname = HnsField(0, 4, 0, 32, false, 1)
        val ev = HnsField(4, 4, 0, 32, false, 1)
        val iv = HnsField(8, 4, 0, 32, false, 1)
        val moves = HnsField(12, 8, 0, 64, false, 4)
        val species = HnsField(20, 2, 0, 16, false, 1)
        val heldItem = HnsField(22, 2, 0, 16, false, 1)
        val ability = HnsField(24, 2, 0, 16, false, 1)
        val lvl = HnsField(26, 1, 0, 8, false, 1)
        val ball = HnsField(27, 1, 0, 8, false, 1)
        val friendship = HnsField(28, 1, 0, 8, false, 1)
        val gender = HnsField(29, 1, 5, 2, false, 1)
        val isShiny = HnsField(29, 1, 7, 1, false, 1)
        val nature = HnsField(29, 1, 0, 5, false, 1)
        val gigantamaxFactor = HnsField(30, 1, 5, 1, false, 1)
        val padding1 = HnsField(30, 1, 7, 1, false, 1)
        val shouldUseDynamax = HnsField(30, 1, 6, 1, false, 1)
        val teraType = HnsField(30, 1, 0, 5, false, 1)
        val dynamaxLevel = HnsField(31, 1, 0, 4, false, 1)
        val padding2 = HnsField(31, 1, 4, 4, false, 1)
        val tags = HnsField(32, 4, 0, 32, false, 1)
    }
    object TrainerClass {
        const val SIZE = 16
        val name = HnsField(0, 13, 0, 104, false, 13)
        val money = HnsField(13, 1, 0, 8, false, 1)
        val ball = HnsField(14, 2, 0, 16, false, 1)
    }
    object TrainerBattleParameter {
        const val SIZE = 40
        val isDoubleBattle = HnsField(0, 1, 0, 1, false, 1)
        val isRematch = HnsField(0, 1, 1, 1, false, 1)
        val mode = HnsField(0, 1, 4, 4, false, 1)
        val playMusicA = HnsField(0, 1, 2, 1, false, 1)
        val playMusicB = HnsField(0, 1, 3, 1, false, 1)
        val objEventLocalIdA = HnsField(1, 1, 0, 8, false, 1)
        val opponentA = HnsField(2, 2, 0, 16, false, 1)
        val introTextA = HnsField(4, 4, 0, 32, false, 1)
        val defeatTextA = HnsField(8, 4, 0, 32, false, 1)
        val battleScriptRetAddrA = HnsField(12, 4, 0, 32, false, 1)
        val objEventLocalIdB = HnsField(16, 1, 0, 8, false, 1)
        val opponentB = HnsField(17, 2, 0, 16, false, 1)
        val introTextB = HnsField(19, 4, 0, 32, false, 1)
        val defeatTextB = HnsField(23, 4, 0, 32, false, 1)
        val battleScriptRetAddrB = HnsField(27, 4, 0, 32, false, 1)
        val victoryText = HnsField(31, 4, 0, 32, false, 1)
        val cannotBattleText = HnsField(35, 4, 0, 32, false, 1)
        val rivalBattleFlags = HnsField(39, 1, 0, 8, false, 1)
    }
    object WildPokemonHeader {
        const val SIZE = 84
        val mapGroup = HnsField(0, 1, 0, 8, false, 1)
        val mapNum = HnsField(1, 1, 0, 8, false, 1)
        val encounterTypes = HnsField(4, 80, 0, 640, false, 4)
    }
    object WildEncounterTypes {
        const val SIZE = 20
        val landMonsInfo = HnsField(0, 4, 0, 32, false, 1)
        val waterMonsInfo = HnsField(4, 4, 0, 32, false, 1)
        val rockSmashMonsInfo = HnsField(8, 4, 0, 32, false, 1)
        val fishingMonsInfo = HnsField(12, 4, 0, 32, false, 1)
        val hiddenMonsInfo = HnsField(16, 4, 0, 32, false, 1)
    }
    object WildPokemonInfo {
        const val SIZE = 8
        val encounterRate = HnsField(0, 1, 0, 8, false, 1)
        val wildPokemon = HnsField(4, 4, 0, 32, false, 1)
    }
    object WildPokemon {
        const val SIZE = 4
        val minLevel = HnsField(0, 1, 0, 8, false, 1)
        val maxLevel = HnsField(1, 1, 0, 8, false, 1)
        val species = HnsField(2, 2, 0, 16, false, 1)
    }
    object BattleResults {
        const val SIZE = 92
        val playerFaintCounter = HnsField(0, 1, 0, 8, false, 1)
        val opponentFaintCounter = HnsField(1, 1, 0, 8, false, 1)
        val playerSwitchesCounter = HnsField(2, 1, 0, 8, false, 1)
        val numHealingItemsUsed = HnsField(3, 1, 0, 8, false, 1)
        val numRevivesUsed = HnsField(4, 1, 0, 8, false, 1)
        val caughtMonBall = HnsField(5, 1, 1, 4, false, 1)
        val playerMonWasDamaged = HnsField(5, 1, 0, 1, false, 1)
        val shinyWildMon = HnsField(5, 1, 5, 1, false, 1)
        val playerMon1Species = HnsField(6, 2, 0, 16, false, 1)
        val playerMon1Name = HnsField(8, 13, 0, 104, false, 13)
        val battleTurnCounter = HnsField(21, 1, 0, 8, false, 1)
        val playerMon2Name = HnsField(22, 13, 0, 104, false, 13)
        val pokeblockThrows = HnsField(35, 1, 0, 8, false, 1)
        val lastOpponentSpecies = HnsField(36, 2, 0, 16, false, 1)
        val lastUsedMovePlayer = HnsField(38, 2, 0, 16, false, 1)
        val lastUsedMoveOpponent = HnsField(40, 2, 0, 16, false, 1)
        val playerMon2Species = HnsField(42, 2, 0, 16, false, 1)
        val caughtMonSpecies = HnsField(44, 2, 0, 16, false, 1)
        val caughtMonNick = HnsField(46, 13, 0, 104, false, 13)
        val filler35 = HnsField(59, 1, 0, 8, false, 1)
        val catchAttempts = HnsField(60, 29, 0, 232, false, 29)
    }
    object MapHeader {
        const val SIZE = 28
        val mapLayout = HnsField(0, 4, 0, 32, false, 1)
        val events = HnsField(4, 4, 0, 32, false, 1)
        val mapScripts = HnsField(8, 4, 0, 32, false, 1)
        val connections = HnsField(12, 4, 0, 32, false, 1)
        val music = HnsField(16, 2, 0, 16, false, 1)
        val mapLayoutId = HnsField(18, 2, 0, 16, false, 1)
        val regionMapSectionId = HnsField(20, 1, 0, 8, false, 1)
        val cave = HnsField(21, 1, 0, 8, false, 1)
        val weather = HnsField(22, 1, 0, 8, false, 1)
        val mapType = HnsField(23, 1, 0, 8, false, 1)
        val filler_18 = HnsField(24, 2, 0, 16, false, 2)
        val allowCycling = HnsField(26, 1, 0, 1, false, 1)
        val allowEscaping = HnsField(26, 1, 1, 1, false, 1)
        val allowRunning = HnsField(26, 1, 2, 1, false, 1)
        val showMapName = HnsField(26, 1, 3, 5, false, 1)
        val battleType = HnsField(27, 1, 0, 8, false, 1)
    }
    object RegionMapLocation {
        const val SIZE = 8
        val x = HnsField(0, 1, 0, 8, false, 1)
        val y = HnsField(1, 1, 0, 8, false, 1)
        val width = HnsField(2, 1, 0, 8, false, 1)
        val height = HnsField(3, 1, 0, 8, false, 1)
        val name = HnsField(4, 4, 0, 32, false, 1)
    }
    object WarpData {
        const val SIZE = 8
        val mapGroup = HnsField(0, 1, 0, 8, true, 1)
        val mapNum = HnsField(1, 1, 0, 8, true, 1)
        val warpId = HnsField(2, 1, 0, 8, true, 1)
        val x = HnsField(4, 2, 0, 16, true, 1)
        val y = HnsField(6, 2, 0, 16, true, 1)
    }
    object SaveBlock1 {
        const val SIZE = 15760
        val pos = HnsField(4, 4, 0, 32, false, 1)
        val location = HnsField(8, 8, 0, 64, false, 1)
        val playerPartyCount = HnsField(568, 1, 0, 8, false, 1)
        val money = HnsField(1172, 4, 0, 32, false, 1)
        val bag = HnsField(1380, 2612, 0, 20896, false, 1)
        val flags = HnsField(6540, 304, 0, 2432, false, 304)
        val vars = HnsField(6844, 512, 0, 4096, false, 256)
        val gameStats = HnsField(7356, 256, 0, 2048, false, 64)
        val dexSeen = HnsField(14784, 136, 0, 1088, false, 136)
        val dexCaught = HnsField(14975, 136, 0, 1088, false, 136)
    }
    object SaveBlock2 {
        const val SIZE = 3892
        val playerName = HnsField(0, 8, 0, 64, false, 8)
        val playerGender = HnsField(8, 1, 0, 8, false, 1)
        val playerTrainerId = HnsField(10, 4, 0, 32, false, 4)
        val optionsBattleStyle = HnsField(21, 1, 1, 1, false, 1)
        val encryptionKey = HnsField(172, 4, 0, 32, false, 1)
        val rivalName = HnsField(3884, 8, 0, 64, false, 8)
    }
    object BattleScripting {
        const val SIZE = 60
        val battler = HnsField(23, 1, 0, 8, false, 1)
    }
    object BattleStruct {
        const val SIZE = 992
        val futureSight = HnsField(160, 16, 0, 128, false, 4)
        val wish = HnsField(176, 16, 0, 128, false, 4)
        val weatherDuration = HnsField(208, 1, 0, 8, false, 1)
        val unableToUseMove = HnsField(302, 1, 3, 1, false, 1)
    }
    object SideTimer {
        const val SIZE = 32
        val reflectTimer = HnsField(0, 2, 0, 16, false, 1)
        val lightscreenTimer = HnsField(2, 2, 0, 16, false, 1)
        val mistTimer = HnsField(4, 2, 0, 16, false, 1)
        val safeguardTimer = HnsField(6, 2, 0, 16, false, 1)
        val spikesAmount = HnsField(8, 1, 0, 4, false, 1)
        val toxicSpikesAmount = HnsField(8, 1, 4, 4, false, 1)
        val stickyWebBattlerId = HnsField(9, 1, 0, 8, false, 1)
        val stickyWebBattlerSide = HnsField(10, 1, 0, 8, false, 1)
        val auroraVeilTimer = HnsField(12, 2, 0, 16, false, 1)
        val tailwindTimer = HnsField(14, 2, 0, 16, false, 1)
        val luckyChantTimer = HnsField(16, 2, 0, 16, false, 1)
        val followmePowder = HnsField(18, 1, 7, 1, false, 1)
        val followmeTarget = HnsField(18, 1, 4, 3, false, 1)
        val followmeTimer = HnsField(18, 1, 0, 4, false, 1)
        val retaliateTimer = HnsField(19, 1, 0, 8, false, 1)
        val damageNonTypesTimer = HnsField(20, 2, 0, 16, false, 1)
        val damageNonTypesType = HnsField(22, 1, 0, 8, false, 1)
        val rainbowTimer = HnsField(24, 2, 0, 16, false, 1)
        val seaOfFireTimer = HnsField(26, 2, 0, 16, false, 1)
        val swampTimer = HnsField(28, 2, 0, 16, false, 1)
    }
    object FieldTimer {
        const val SIZE = 16
        val mudSportTimer = HnsField(0, 2, 0, 16, false, 1)
        val waterSportTimer = HnsField(2, 2, 0, 16, false, 1)
        val wonderRoomTimer = HnsField(4, 2, 0, 16, false, 1)
        val magicRoomTimer = HnsField(6, 2, 0, 16, false, 1)
        val trickRoomTimer = HnsField(8, 2, 0, 16, false, 1)
        val terrainTimer = HnsField(10, 2, 0, 16, false, 1)
        val gravityTimer = HnsField(12, 2, 0, 16, false, 1)
        val fairyLockTimer = HnsField(14, 2, 0, 16, false, 1)
    }
    object ProtectStruct {
        const val SIZE = 12
        val physicalDmg = HnsField(6, 2, 0, 16, false, 1)
        val specialDmg = HnsField(8, 2, 0, 16, false, 1)
    }
    object Main {
        const val SIZE = 1084
        val callback2 = HnsField(4, 4, 0, 32, false, 1)
        val savedCallback = HnsField(8, 4, 0, 32, false, 1)
        val oamBuffer = HnsField(56, 1024, 0, 8192, false, 128)
    }
    object Sprite {
        const val SIZE = 68
        val oam = HnsField(0, 8, 0, 64, false, 1)
        val x = HnsField(32, 2, 0, 16, true, 1)
        val y = HnsField(34, 2, 0, 16, true, 1)
        val x2 = HnsField(36, 2, 0, 16, true, 1)
        val y2 = HnsField(38, 2, 0, 16, true, 1)
        val centerToCornerVecX = HnsField(40, 1, 0, 8, true, 1)
        val centerToCornerVecY = HnsField(41, 1, 0, 8, true, 1)
        val coordOffsetEnabled = HnsField(62, 1, 1, 1, false, 1)
        val inUse = HnsField(62, 1, 0, 1, false, 1)
        val invisible = HnsField(62, 1, 2, 1, false, 1)
    }
    object ObjectEvent {
        const val SIZE = 36
        val facingDirection = HnsField(24, 1, 0, 4, false, 1)
    }
    object PlayerAvatar {
        const val SIZE = 40
        val runningState = HnsField(2, 1, 0, 7, false, 1)
        val tileTransitionState = HnsField(3, 1, 0, 8, false, 1)
        val spriteId = HnsField(4, 1, 0, 8, false, 1)
        val objectEventId = HnsField(5, 1, 0, 8, false, 1)
    }
}
