package com.ironmonone.app.engine.hns

/**
 * What a mode asks of the Heart & Soul engine: the options of a UPR settings file (.rnqs), read from the Nat. Dex
 * fork's Settings (the RSE NatDex v1.2 presets) or ZX's (the vanilla RSE presets) into one shape. Enum options keep the
 * UPR enum constant's name ("RANDOM", "AREA_MAPPING"), which both forks share. The options are the union of what the
 * RSE presets set (decoded 2026-10-05; the list is in docs/HNS-KAIZO.md, HnsEngine); [HnsRandomizer.unsupported] names
 * any other option a file sets, and the log says it was not applied.
 */
data class HnsOptions(
    val modeName: String,
    val settingsString: String,
    /** The settings came from a ZX file (vanilla RSE presets): ZX's move and ability pools apply (HnsUprRules). */
    val zxRules: Boolean = false,
    val limitPokemon: Boolean = false,
    val banLuckyEgg: Boolean = false,
    val miscTweaks: Int = 0,
    // Evolutions
    val changeImpossibleEvolutions: Boolean = false,
    val makeEvolutionsEasier: Boolean = false,
    val removeTimeBasedEvolutions: Boolean = false,
    val evolutionsMod: String = "UNCHANGED",
    val evosSimilarStrength: Boolean = false,
    val evosSameTyping: Boolean = false,
    val evosMaxThreeStages: Boolean = false,
    val evosForceChange: Boolean = false,
    val evosMatchPostEvoTyping: Boolean = false,
    // Pokemon traits
    val baseStatsMod: String = "UNCHANGED",
    val baseStatsFollowEvolutions: Boolean = false,
    val updateBaseStats: Boolean = false,
    val standardizeExpCurves: Boolean = false,
    val expCurve: String = "MEDIUM_FAST",
    val expCurveMod: String = "LEGENDARIES",
    val typesMod: String = "UNCHANGED",
    val dualTypeOnly: Boolean = false,
    val abilitiesMod: String = "UNCHANGED",
    val allowWonderGuard: Boolean = true,
    val abilitiesFollowEvolutions: Boolean = false,
    val banTrappingAbilities: Boolean = false,
    val banNegativeAbilities: Boolean = false,
    val banBadAbilities: Boolean = false,
    val weighDuplicateAbilities: Boolean = false,
    val ensureTwoAbilities: Boolean = false,
    // Starters
    val startersMod: String = "UNCHANGED",
    val customStarters: List<Int> = emptyList(),
    val randomizeStarterHeldItems: Boolean = false,
    val banBadStarterHeldItems: Boolean = false,
    // Moves
    val randomizeMovePowers: Boolean = false,
    val randomizeMoveAccuracies: Boolean = false,
    val randomizeMovePPs: Boolean = false,
    val randomizeMoveTypes: Boolean = false,
    val randomizeMoveCategory: Boolean = false,
    val updateMoves: Boolean = false,
    val movesetsMod: String = "UNCHANGED",
    val startWithGuaranteedMoves: Boolean = false,
    val guaranteedMoveCount: Int = 2,
    val evolutionMovesForAll: Boolean = false,
    val movesetsForceGoodDamaging: Boolean = false,
    val movesetsGoodDamagingPercent: Int = 0,
    val reorderDamagingMoves: Boolean = false,
    val blockBrokenMovesetMoves: Boolean = false,
    // TMs and tutors
    val tmsMod: String = "UNCHANGED",
    val keepFieldMoveTMs: Boolean = false,
    val tmsForceGoodDamaging: Boolean = false,
    val fullHMCompat: Boolean = false,
    val tmCompatMod: String = "UNCHANGED",
    val tmLevelUpMoveSanity: Boolean = false,
    val tmsFollowEvolutions: Boolean = false,
    val tutorMovesMod: String = "UNCHANGED",
    val tutorCompatMod: String = "UNCHANGED",
    val tutorFollowEvolutions: Boolean = false,
    val tutorLevelUpMoveSanity: Boolean = false,
    // Trainers
    val trainersMod: String = "UNCHANGED",
    val rivalCarriesStarter: Boolean = false,
    val trainersSimilarStrength: Boolean = false,
    val trainersMatchTypingDistribution: Boolean = false,
    val trainersBlockLegendaries: Boolean = true,
    val trainersBlockEarlyWonderGuard: Boolean = true,
    val randomizeTrainerNames: Boolean = false,
    val randomizeTrainerClassNames: Boolean = false,
    val trainersForceFullyEvolved: Boolean = false,
    val trainersForceFullyEvolvedLevel: Int = 30,
    val trainersLevelModified: Boolean = false,
    val trainersLevelModifier: Int = 0,
    val eliteFourUniquePokemon: Int = 0,
    val smartAi: Boolean = false,
    val additionalBossPokemon: Int = 0,
    val additionalImportantPokemon: Int = 0,
    val additionalRegularPokemon: Int = 0,
    val heldItemsBoss: Boolean = false,
    val heldItemsImportant: Boolean = false,
    val heldItemsRegular: Boolean = false,
    val consumableItemsOnly: Boolean = false,
    val sensibleItemsOnly: Boolean = false,
    val highestLevelGetsItems: Boolean = false,
    val doubleBattleMode: Boolean = false,
    val shinyChance: Boolean = false,
    val betterTrainerMovesets: Boolean = false,
    val allowTrainerAltFormes: Boolean = false,
    // Wild
    val wildMod: String = "UNCHANGED",
    val wildRestrictionMod: String = "NONE",
    val useTimeBasedEncounters: Boolean = false,
    val blockWildLegendaries: Boolean = true,
    val useMinimumCatchRate: Boolean = false,
    val minimumCatchRateLevel: Int = 1,
    val randomizeWildHeldItems: Boolean = false,
    val banBadWildHeldItems: Boolean = false,
    val wildLevelsModified: Boolean = false,
    val wildLevelModifier: Int = 0,
    /** 0: no legendary ban beyond [blockWildLegendaries] as legendaries and ultra beasts; 1: all legendaries; 2: strong legendaries only. */
    val wildBSTLimitMode: Int = 0,
    val wildPokemonBSTLimit: Int = 0,
    // Statics
    val staticMod: String = "UNCHANGED",
    val staticLevelModified: Boolean = false,
    val staticLevelModifier: Int = 0,
    // Trades and items
    val tradesMod: String = "UNCHANGED",
    val randomizeTradeNicknames: Boolean = false,
    val randomizeTradeOTs: Boolean = false,
    val randomizeTradeIVs: Boolean = false,
    val randomizeTradeItems: Boolean = false,
    val fieldItemsMod: String = "UNCHANGED",
    val banBadFieldItems: Boolean = false,
    val shopItemsMod: String = "UNCHANGED",
    val pickupItemsMod: String = "UNCHANGED",
    val banBadPickupItems: Boolean = false,
    // UPR's bundled custom names (trainer names, classes, nicknames)
    val trainerNames: List<String> = emptyList(),
    val doublesTrainerNames: List<String> = emptyList(),
    val trainerClassNames: List<String> = emptyList(),
    val doublesTrainerClassNames: List<String> = emptyList(),
    val pokemonNicknames: List<String> = emptyList(),
) {
    companion object {
        /** The options of a Nat. Dex settings file, the RSE NatDex v1.2 presets' class. */
        fun from(s: com.dabomstew.pkrandom.Settings, modeName: String): HnsOptions {
            val names = runCatching { com.dabomstew.pkrandom.FileFunctions.getCustomNames() }.getOrNull()
            return HnsOptions(
                modeName = modeName,
                settingsString = runCatching { com.dabomstew.pkrandom.Version.VERSION.toString() + s.toString() }.getOrDefault(""),
                limitPokemon = s.isLimitPokemon,
                banLuckyEgg = (s.currentMiscTweaks and com.dabomstew.pkrandom.MiscTweak.BAN_LUCKY_EGG.value) != 0,
                miscTweaks = s.currentMiscTweaks,
                changeImpossibleEvolutions = s.isChangeImpossibleEvolutions,
                makeEvolutionsEasier = s.isMakeEvolutionsEasier,
                removeTimeBasedEvolutions = s.isRemoveTimeBasedEvolutions,
                evolutionsMod = s.evolutionsMod.name,
                evosSimilarStrength = s.isEvosSimilarStrength,
                evosSameTyping = s.isEvosSameTyping,
                evosMaxThreeStages = s.isEvosMaxThreeStages,
                evosForceChange = s.isEvosForceChange,
                evosMatchPostEvoTyping = s.isEvosMatchPostEvoTyping,
                baseStatsMod = s.baseStatisticsMod.name,
                baseStatsFollowEvolutions = s.isBaseStatsFollowEvolutions,
                updateBaseStats = s.isUpdateBaseStats,
                standardizeExpCurves = s.isStandardizeEXPCurves,
                expCurve = s.selectedEXPCurve?.name ?: "MEDIUM_FAST",
                expCurveMod = s.expCurveMod?.name ?: "LEGENDARIES",
                typesMod = s.typesMod.name,
                dualTypeOnly = s.isDualTypeOnly,
                abilitiesMod = s.abilitiesMod.name,
                allowWonderGuard = s.isAllowWonderGuard,
                abilitiesFollowEvolutions = s.isAbilitiesFollowEvolutions,
                banTrappingAbilities = s.isBanTrappingAbilities,
                banNegativeAbilities = s.isBanNegativeAbilities,
                banBadAbilities = s.isBanBadAbilities,
                weighDuplicateAbilities = s.isWeighDuplicateAbilitiesTogether,
                ensureTwoAbilities = s.isEnsureTwoAbilities,
                startersMod = s.startersMod.name,
                customStarters = s.customStarters?.toList() ?: emptyList(),
                randomizeStarterHeldItems = s.isRandomizeStartersHeldItems,
                banBadStarterHeldItems = s.isBanBadRandomStarterHeldItems,
                randomizeMovePowers = s.isRandomizeMovePowers,
                randomizeMoveAccuracies = s.isRandomizeMoveAccuracies,
                randomizeMovePPs = s.isRandomizeMovePPs,
                randomizeMoveTypes = s.isRandomizeMoveTypes,
                randomizeMoveCategory = s.isRandomizeMoveCategory,
                updateMoves = s.isUpdateMoves,
                movesetsMod = s.movesetsMod.name,
                startWithGuaranteedMoves = s.isStartWithGuaranteedMoves,
                guaranteedMoveCount = s.guaranteedMoveCount,
                evolutionMovesForAll = s.isEvolutionMovesForAll,
                movesetsForceGoodDamaging = s.isMovesetsForceGoodDamaging,
                movesetsGoodDamagingPercent = s.movesetsGoodDamagingPercent,
                reorderDamagingMoves = s.isReorderDamagingMoves,
                blockBrokenMovesetMoves = s.isBlockBrokenMovesetMoves,
                tmsMod = s.tmsMod.name,
                keepFieldMoveTMs = s.isKeepFieldMoveTMs,
                tmsForceGoodDamaging = s.isTmsForceGoodDamaging,
                fullHMCompat = s.isFullHMCompat,
                tmCompatMod = s.tmsHmsCompatibilityMod.name,
                tmLevelUpMoveSanity = s.isTmLevelUpMoveSanity,
                tmsFollowEvolutions = s.isTmsFollowEvolutions,
                tutorMovesMod = s.moveTutorMovesMod.name,
                tutorCompatMod = s.moveTutorsCompatibilityMod.name,
                tutorFollowEvolutions = s.isTutorFollowEvolutions,
                tutorLevelUpMoveSanity = s.isTutorLevelUpMoveSanity,
                trainersMod = s.trainersMod.name,
                rivalCarriesStarter = s.isRivalCarriesStarterThroughout,
                trainersSimilarStrength = s.isTrainersUsePokemonOfSimilarStrength,
                trainersMatchTypingDistribution = s.isTrainersMatchTypingDistribution,
                trainersBlockLegendaries = s.isTrainersBlockLegendaries,
                trainersBlockEarlyWonderGuard = s.isTrainersBlockEarlyWonderGuard,
                randomizeTrainerNames = s.isRandomizeTrainerNames,
                randomizeTrainerClassNames = s.isRandomizeTrainerClassNames,
                trainersForceFullyEvolved = s.isTrainersForceFullyEvolved,
                trainersForceFullyEvolvedLevel = s.trainersForceFullyEvolvedLevel,
                trainersLevelModified = s.isTrainersLevelModified,
                trainersLevelModifier = s.trainersLevelModifier,
                eliteFourUniquePokemon = s.eliteFourUniquePokemonNumber,
                smartAi = s.isSwapTrainerMegaEvos,
                additionalBossPokemon = s.additionalBossTrainerPokemon,
                additionalImportantPokemon = s.additionalImportantTrainerPokemon,
                additionalRegularPokemon = s.additionalRegularTrainerPokemon,
                heldItemsBoss = s.isRandomizeHeldItemsForBossTrainerPokemon,
                heldItemsImportant = s.isRandomizeHeldItemsForImportantTrainerPokemon,
                heldItemsRegular = s.isRandomizeHeldItemsForRegularTrainerPokemon,
                consumableItemsOnly = s.isConsumableItemsOnlyForTrainers,
                sensibleItemsOnly = s.isSensibleItemsOnlyForTrainers,
                highestLevelGetsItems = s.isHighestLevelGetsItemsForTrainers,
                doubleBattleMode = s.isDoubleBattleMode,
                shinyChance = s.isShinyChance,
                betterTrainerMovesets = s.isBetterTrainerMovesets,
                allowTrainerAltFormes = s.isAllowTrainerAlternateFormes,
                wildMod = s.wildPokemonMod.name,
                wildRestrictionMod = s.wildPokemonRestrictionMod.name,
                useTimeBasedEncounters = s.isUseTimeBasedEncounters,
                blockWildLegendaries = s.isBlockWildLegendaries,
                useMinimumCatchRate = s.isUseMinimumCatchRate,
                minimumCatchRateLevel = s.minimumCatchRateLevel,
                randomizeWildHeldItems = s.isRandomizeWildPokemonHeldItems,
                banBadWildHeldItems = s.isBanBadRandomWildPokemonHeldItems,
                wildLevelsModified = s.isWildLevelsModified,
                wildLevelModifier = s.wildLevelModifier,
                wildBSTLimitMode = s.wildBSTLimit,
                wildPokemonBSTLimit = s.wildPokemonBSTLimit,
                staticMod = s.staticPokemonMod.name,
                staticLevelModified = s.isStaticLevelModified,
                staticLevelModifier = s.staticLevelModifier,
                tradesMod = s.inGameTradesMod.name,
                randomizeTradeNicknames = s.isRandomizeInGameTradesNicknames,
                randomizeTradeOTs = s.isRandomizeInGameTradesOTs,
                randomizeTradeIVs = s.isRandomizeInGameTradesIVs,
                randomizeTradeItems = s.isRandomizeInGameTradesItems,
                fieldItemsMod = s.fieldItemsMod.name,
                banBadFieldItems = s.isBanBadRandomFieldItems,
                shopItemsMod = s.shopItemsMod.name,
                pickupItemsMod = s.pickupItemsMod.name,
                banBadPickupItems = s.isBanBadRandomPickupItems,
                trainerNames = names?.trainerNames.orEmpty(),
                doublesTrainerNames = names?.doublesTrainerNames.orEmpty(),
                trainerClassNames = names?.trainerClasses.orEmpty(),
                doublesTrainerClassNames = names?.doublesTrainerClasses.orEmpty(),
                pokemonNicknames = names?.pokemonNicknames.orEmpty(),
            )
        }

        /**
         * The options of a ZX settings file (the vanilla RSE presets). ZX has no wild BST line and no "match post-evo
         * typing"; its legendary ban is the plain one.
         */
        fun fromZx(s: com.dabomstew.pkrandomzx.Settings, modeName: String): HnsOptions {
            val names = runCatching { com.dabomstew.pkrandom.FileFunctions.getCustomNames() }.getOrNull()
            return HnsOptions(
                modeName = modeName,
                settingsString = runCatching { com.dabomstew.pkrandomzx.Version.VERSION.toString() + s.toString() }.getOrDefault(""),
                zxRules = true,
                limitPokemon = s.isLimitPokemon,
                banLuckyEgg = (s.currentMiscTweaks and com.dabomstew.pkrandomzx.MiscTweak.BAN_LUCKY_EGG.value) != 0,
                miscTweaks = s.currentMiscTweaks,
                changeImpossibleEvolutions = s.isChangeImpossibleEvolutions,
                makeEvolutionsEasier = s.isMakeEvolutionsEasier,
                removeTimeBasedEvolutions = s.isRemoveTimeBasedEvolutions,
                evolutionsMod = s.evolutionsMod.name,
                evosSimilarStrength = s.isEvosSimilarStrength,
                evosSameTyping = s.isEvosSameTyping,
                evosMaxThreeStages = s.isEvosMaxThreeStages,
                evosForceChange = s.isEvosForceChange,
                baseStatsMod = s.baseStatisticsMod.name,
                baseStatsFollowEvolutions = s.isBaseStatsFollowEvolutions,
                updateBaseStats = s.isUpdateBaseStats,
                standardizeExpCurves = s.isStandardizeEXPCurves,
                expCurve = s.selectedEXPCurve?.name ?: "MEDIUM_FAST",
                expCurveMod = s.expCurveMod?.name ?: "LEGENDARIES",
                typesMod = s.typesMod.name,
                dualTypeOnly = s.isDualTypeOnly,
                abilitiesMod = s.abilitiesMod.name,
                allowWonderGuard = s.isAllowWonderGuard,
                abilitiesFollowEvolutions = s.isAbilitiesFollowEvolutions,
                banTrappingAbilities = s.isBanTrappingAbilities,
                banNegativeAbilities = s.isBanNegativeAbilities,
                banBadAbilities = s.isBanBadAbilities,
                weighDuplicateAbilities = s.isWeighDuplicateAbilitiesTogether,
                ensureTwoAbilities = s.isEnsureTwoAbilities,
                startersMod = s.startersMod.name,
                customStarters = s.customStarters?.toList() ?: emptyList(),
                randomizeStarterHeldItems = s.isRandomizeStartersHeldItems,
                banBadStarterHeldItems = s.isBanBadRandomStarterHeldItems,
                randomizeMovePowers = s.isRandomizeMovePowers,
                randomizeMoveAccuracies = s.isRandomizeMoveAccuracies,
                randomizeMovePPs = s.isRandomizeMovePPs,
                randomizeMoveTypes = s.isRandomizeMoveTypes,
                randomizeMoveCategory = s.isRandomizeMoveCategory,
                updateMoves = s.isUpdateMoves,
                movesetsMod = s.movesetsMod.name,
                startWithGuaranteedMoves = s.isStartWithGuaranteedMoves,
                guaranteedMoveCount = s.guaranteedMoveCount,
                evolutionMovesForAll = s.isEvolutionMovesForAll,
                movesetsForceGoodDamaging = s.isMovesetsForceGoodDamaging,
                movesetsGoodDamagingPercent = s.movesetsGoodDamagingPercent,
                reorderDamagingMoves = s.isReorderDamagingMoves,
                blockBrokenMovesetMoves = s.isBlockBrokenMovesetMoves,
                tmsMod = s.tmsMod.name,
                keepFieldMoveTMs = s.isKeepFieldMoveTMs,
                tmsForceGoodDamaging = s.isTmsForceGoodDamaging,
                fullHMCompat = s.isFullHMCompat,
                tmCompatMod = s.tmsHmsCompatibilityMod.name,
                tmLevelUpMoveSanity = s.isTmLevelUpMoveSanity,
                tmsFollowEvolutions = s.isTmsFollowEvolutions,
                tutorMovesMod = s.moveTutorMovesMod.name,
                tutorCompatMod = s.moveTutorsCompatibilityMod.name,
                tutorFollowEvolutions = s.isTutorFollowEvolutions,
                tutorLevelUpMoveSanity = s.isTutorLevelUpMoveSanity,
                trainersMod = s.trainersMod.name,
                rivalCarriesStarter = s.isRivalCarriesStarterThroughout,
                trainersSimilarStrength = s.isTrainersUsePokemonOfSimilarStrength,
                trainersMatchTypingDistribution = s.isTrainersMatchTypingDistribution,
                trainersBlockLegendaries = s.isTrainersBlockLegendaries,
                trainersBlockEarlyWonderGuard = s.isTrainersBlockEarlyWonderGuard,
                randomizeTrainerNames = s.isRandomizeTrainerNames,
                randomizeTrainerClassNames = s.isRandomizeTrainerClassNames,
                trainersForceFullyEvolved = s.isTrainersForceFullyEvolved,
                trainersForceFullyEvolvedLevel = s.trainersForceFullyEvolvedLevel,
                trainersLevelModified = s.isTrainersLevelModified,
                trainersLevelModifier = s.trainersLevelModifier,
                eliteFourUniquePokemon = s.eliteFourUniquePokemonNumber,
                smartAi = s.isSwapTrainerMegaEvos,
                additionalBossPokemon = s.additionalBossTrainerPokemon,
                additionalImportantPokemon = s.additionalImportantTrainerPokemon,
                additionalRegularPokemon = s.additionalRegularTrainerPokemon,
                heldItemsBoss = s.isRandomizeHeldItemsForBossTrainerPokemon,
                heldItemsImportant = s.isRandomizeHeldItemsForImportantTrainerPokemon,
                heldItemsRegular = s.isRandomizeHeldItemsForRegularTrainerPokemon,
                consumableItemsOnly = s.isConsumableItemsOnlyForTrainers,
                sensibleItemsOnly = s.isSensibleItemsOnlyForTrainers,
                highestLevelGetsItems = s.isHighestLevelGetsItemsForTrainers,
                doubleBattleMode = s.isDoubleBattleMode,
                shinyChance = s.isShinyChance,
                betterTrainerMovesets = s.isBetterTrainerMovesets,
                allowTrainerAltFormes = s.isAllowTrainerAlternateFormes,
                wildMod = s.wildPokemonMod.name,
                wildRestrictionMod = s.wildPokemonRestrictionMod.name,
                useTimeBasedEncounters = s.isUseTimeBasedEncounters,
                blockWildLegendaries = s.isBlockWildLegendaries,
                useMinimumCatchRate = s.isUseMinimumCatchRate,
                minimumCatchRateLevel = s.minimumCatchRateLevel,
                randomizeWildHeldItems = s.isRandomizeWildPokemonHeldItems,
                banBadWildHeldItems = s.isBanBadRandomWildPokemonHeldItems,
                wildLevelsModified = s.isWildLevelsModified,
                wildLevelModifier = s.wildLevelModifier,
                wildBSTLimitMode = 1,
                wildPokemonBSTLimit = 0,
                staticMod = s.staticPokemonMod.name,
                staticLevelModified = s.isStaticLevelModified,
                staticLevelModifier = s.staticLevelModifier,
                tradesMod = s.inGameTradesMod.name,
                randomizeTradeNicknames = s.isRandomizeInGameTradesNicknames,
                randomizeTradeOTs = s.isRandomizeInGameTradesOTs,
                randomizeTradeIVs = s.isRandomizeInGameTradesIVs,
                randomizeTradeItems = s.isRandomizeInGameTradesItems,
                fieldItemsMod = s.fieldItemsMod.name,
                banBadFieldItems = s.isBanBadRandomFieldItems,
                shopItemsMod = s.shopItemsMod.name,
                pickupItemsMod = s.pickupItemsMod.name,
                banBadPickupItems = s.isBanBadRandomPickupItems,
                trainerNames = names?.trainerNames.orEmpty(),
                doublesTrainerNames = names?.doublesTrainerNames.orEmpty(),
                trainerClassNames = names?.trainerClasses.orEmpty(),
                doublesTrainerClassNames = names?.doublesTrainerClasses.orEmpty(),
                pokemonNicknames = names?.pokemonNicknames.orEmpty(),
            )
        }
    }
}
