"""Extract which settings the desktop randomizer HIDES for a whole generation.

The GUI hides a control with `setVisible(romHandler.hasX())`. Only
capabilities whose concrete RomHandler returns a LITERAL are taken:

    public boolean hasMegaEvolutions() { return false; }      <- a fact about
                                                                 the generation
    public boolean hasMoveTutors() { return romEntry.romType == ...; }
                                                              <- depends on the
                                                                 specific ROM

The second kind is SKIPPED rather than guessed. Unlisted means shown, which is
the safe direction: a missing rule leaves a control visible, a wrong rule hides
something the game supports.

This is what stops the editor offering "Base stats follow mega evolutions"
while you are editing a FireRed preset.

Run from the repo root, after tools/extract_upr.py.
"""
import os
import re

V = ".vendor/upr-zx-461/src/com/dabomstew/pkrandom"
GUI = V + "/newgui/NewRandomizerGUI.java"
RES = "editor/src/main/resources"
OUT = RES + "/upr-unsupported.tsv"

src = open(GUI, encoding="utf-8", errors="replace").read()

# component -> settings field (same join as extract_upr.py)
i = src.index("private Settings createSettingsFromState")
body = src[i:src.index("\n    }", i)]
CONTROL = r"\b([a-z]\w*(?:CheckBox|RadioButton|ComboBox|Slider|TextField|Button))\b"
comp2field = {}
for name, args in re.findall(r"settings\.set(\w+)\(([^;]*?)\);", body, re.S):
    field = name[0].lower() + name[1:]
    for c in dict.fromkeys(re.findall(CONTROL, args)):
        comp2field.setdefault(c, field)

vis = re.findall(r"(\w+)\.setVisible\(romHandler\.(\w+)\(\)\)", src)
caps = sorted(set(c for _, c in vis))

rules = set()
for gen in (3, 4, 5):
    path = V + "/romhandlers/Gen%dRomHandler.java" % gen
    if not os.path.exists(path):
        continue
    h = open(path, encoding="utf-8", errors="replace").read()
    for cap in caps:
        m = re.search(
            r"public boolean " + cap + r"\(\)\s*\{\s*return\s+(true|false)\s*;", h)
        if not m or m.group(1) != "false":
            continue
        for comp, c in vis:
            if c == cap and comp in comp2field:
                rules.add((comp2field[comp], "GEN%d" % gen, cap))

os.makedirs(RES, exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("# GENERATED by tools/extract_upr_support.py - do not hand-edit.\n")
    f.write("# Settings the desktop hides for an ENTIRE generation, taken only\n")
    f.write("# from capabilities with a literal return. Unlisted = shown.\n")
    f.write("# settingsField\tgeneration\tcapability\n")
    for r in sorted(rules):
        f.write("\t".join(r) + "\n")
print("%s: %d rules" % (OUT, len(rules)))
for r in sorted(rules):
    if r[1] == "GEN3":
        print("   GEN3 hides", r[0], "(" + r[2] + ")")
