"""Extract the desktop randomizer's ORDER, HELP TEXT and GATING rules.

Three resources, all GENERATED from the vendored UPR source, so none of them
is a hand-kept list that can rot:

  upr-order.tsv   settings field -> position, from NewRandomizerGUI.form
  upr-help.tsv    settings field -> the randomizer's OWN tooltip text
  upr-gating.tsv  settings field -> the master field/value that disables it

Why generated: the Android editor reflects Settings fields, which come back in
an arbitrary order with no descriptions and no idea which control depends on
which. All three facts already exist in the desktop GUI; reading them beats
writing 141 entries by hand and getting them subtly wrong.

Run from the repo root. Re-run if the vendored randomizer is ever updated.
"""
import os
import re

V = ".vendor/upr-zx-461/src/com/dabomstew/pkrandom"
GUI = V + "/newgui/NewRandomizerGUI.java"
FORM = V + "/newgui/NewRandomizerGUI.form"
BUNDLE = V + "/newgui/Bundle.properties"
SETTINGS = V + "/Settings.java"
RES = "editor/src/main/resources"

src = open(GUI, encoding="utf-8", errors="replace").read()
sset = open(SETTINGS, encoding="utf-8", errors="replace").read()

# --------------------------------------------------------------------------
# The one join everything else hangs off: which GUI control writes which field.
# --------------------------------------------------------------------------
i = src.index("private Settings createSettingsFromState")
body = src[i:src.index("\n    }", i)]
setters = re.findall(r"settings\.set(\w+)\(([^;]*?)\);", body, re.S)
CONTROL = r"\b([a-z]\w*(?:CheckBox|RadioButton|ComboBox|Slider|TextField|Button))\b"

# component -> (settings field, index within a multi-radio enum setter or None)
comp2field = {}
for name, args in setters:
    field = name[0].lower() + name[1:]
    comps = list(dict.fromkeys(re.findall(CONTROL, args)))
    # setXMod(a.isSelected(), b.isSelected(), c.isSelected()) is POSITIONAL:
    # Settings.getEnum() maps argument i onto enum constant i.
    multi = len(comps) > 1 and args.count("isSelected()") == len(comps)
    for k, c in enumerate(comps):
        comp2field.setdefault(c, (field, k if multi else None))

# --------------------------------------------------------------------------
# 1. ORDER - the form lists every control in visual order.
# --------------------------------------------------------------------------
form = open(FORM, encoding="utf-8", errors="replace").read()
pos = {c: k for k, c in enumerate(
    m.group(1) for m in re.finditer(r'binding="(\w+)"', form))}

rows = []
for name, args in setters:
    field = name[0].lower() + name[1:]
    comps = list(dict.fromkeys(re.findall(CONTROL, args)))
    p = min((pos[c] for c in comps if c in pos), default=None)
    if p is not None:
        rows.append((p, field, comps[0]))
rows.sort()

os.makedirs(RES, exist_ok=True)
with open(RES + "/upr-order.tsv", "w", encoding="utf-8") as f:
    f.write("# GENERATED by tools/extract_upr.py - do not hand-edit.\n")
    f.write("# settingsField\tthe UPR control that fixes its position\n")
    for _, field, comp in rows:
        f.write(field + "\t" + comp + "\n")
print("upr-order.tsv:  %d fields" % len(rows))

# --------------------------------------------------------------------------
# 2. HELP - the randomizer's own tooltips, keyed through the same map.
#    Fields with no upstream tooltip are ABSENT: the editor shows nothing
#    rather than inventing an explanation.
# --------------------------------------------------------------------------
tips = {}
for line in open(BUNDLE, encoding="utf-8", errors="replace"):
    m = re.match(r"GUI\.(\w+)\.toolTipText=(.*)", line.strip())
    if m:
        raw = m.group(2).replace(chr(92), "")
        # The bundle stores Swing HTML. Strip it to plain text: <br /> becomes
        # a space, tags go, entities resolve. Showing the markup would be
        # worse than showing nothing.
        txt = re.sub(r"<br\s*/?>", " ", raw, flags=re.I)
        txt = re.sub(r"<[^>]+>", "", txt)
        txt = (txt.replace("&nbsp;", " ").replace("&amp;", "&")
                  .replace("&lt;", "<").replace("&gt;", ">"))
        tips[m.group(1)] = " ".join(txt.split())

n = 0
with open(RES + "/upr-help.tsv", "w", encoding="utf-8") as f:
    f.write("# GENERATED - the randomizer's OWN tooltip text.\n")
    f.write("# settingsField\tdescription\n")
    for _, field, comp in rows:
        t = tips.get(comp)
        if t:
            f.write(field + "\t" + t + "\n")
            n += 1
print("upr-help.tsv:   %d descriptions (of %d fields)" % (n, len(rows)))

# --------------------------------------------------------------------------
# 3. GATING - which controls the desktop DISABLES, and when.
#
# Only single-condition `if (someRadio.isSelected()) { x.setEnabled(false) }`
# blocks are taken. enableOrDisableSubControls() also contains compound
# conditions that are not safely derivable this way, so coverage is PARTIAL by
# design and the count is printed. A wrong rule is worse than a missing one:
# a wrongly-greyed control looks like a broken editor.
# --------------------------------------------------------------------------
enums = {m.group(1): [c.strip() for c in m.group(2).split(",") if c.strip()]
         for m in re.finditer(
             r"public enum (\w+) \{\s*([A-Z0-9_,\s]+?)\s*,?\s*\}", sset)}
# Declarations carry initialisers: `private XMod xMod = XMod.UNCHANGED;`
field2enum = {m.group(2): enums[m.group(1)]
              for m in re.finditer(r"private (\w+) (\w+)\s*(?:=[^;]*)?;", sset)
              if m.group(1) in enums}

i = src.index("private void enableOrDisableSubControls")
meth = src[i:src.index("\n    }\n", i)]
gates = set()
for cond, inner in re.findall(
        r"if \((\w+)\.isSelected\(\)\) \{(.*?)\n        \}", meth, re.S):
    cf = comp2field.get(cond)
    if not cf or cf[1] is None:
        continue
    field, idx = cf
    vals = field2enum.get(field)
    if not vals or idx >= len(vals):
        continue
    for t in re.findall(r"(\w+)\.setEnabled\(false\)", inner):
        tf = comp2field.get(t)
        if tf and tf[0] != field:
            gates.add((tf[0], field, vals[idx]))

with open(RES + "/upr-gating.tsv", "w", encoding="utf-8") as f:
    f.write("# GENERATED from enableOrDisableSubControls() single-condition\n")
    f.write("# blocks. Coverage is PARTIAL on purpose - compound conditions\n")
    f.write("# are skipped rather than guessed.\n")
    f.write("# disabledField\twhenField\tequalsValue\n")
    for r in sorted(gates):
        f.write("\t".join(r) + "\n")
print("upr-gating.tsv: %d gating rules" % len(gates))

# --------------------------------------------------------------------------
# 4. PER-GAME SUPPORT - controls the desktop HIDES for a whole generation.
#
# The GUI hides a control with setVisible(romHandler.hasX()). Only capabilities
# whose concrete handler returns a LITERAL is taken: `return false;` is a fact
# about the whole generation, whereas `return romEntry.romType == ...` depends
# on the specific ROM and is skipped rather than guessed. Unlisted = shown.
# --------------------------------------------------------------------------
vis = re.findall(r"(\w+)\.setVisible\(romHandler\.(\w+)\(\)\)", src)
caps = sorted(set(c for _, c in vis))
unsupported = set()
for gen in (3, 4, 5):
    path = V + "/romhandlers/Gen%dRomHandler.java" % gen
    if not os.path.exists(path):
        continue
    h = open(path, encoding="utf-8", errors="replace").read()
    for cap in caps:
        m = re.search(r"public boolean " + cap + r"\(\)\s*\{\s*return\s+(true|false)\s*;", h)
        if not m or m.group(1) != "false":
            continue
        for comp, c in vis:
            if c != cap:
                continue
            tf = comp2field.get(comp)
            if tf:
                unsupported.add((tf[0], "GEN%d" % gen, cap))

with open(RES + "/upr-unsupported.tsv", "w", encoding="utf-8") as f:
    f.write("# GENERATED - settings the desktop HIDES for a whole generation,
")
    f.write("# taken only from capabilities with a literal return.
")
    f.write("# settingsField	generation	capability
")
    for r in sorted(unsupported):
        f.write("	".join(r) + "
")
print("upr-unsupported.tsv: %d rules" % len(unsupported))
