"""Port the PC tracker's Gen III character map into Kotlin.

The Android tracker had a hand-written subset covering only 0-9, A-Z, a-z and
a little punctuation. Everything else fell through to the '?' fallback, so a
held item called "Poke Doll" - the real name carries an e-acute at byte 0x1B -
rendered on screen as "Pok? Doll".

Transcribing 100+ entries by hand is how the next glyph goes missing, so this
reads the reference table instead:

    ironmon-ref/Ironmon-Tracker/ironmon_tracker/GameSettings.lua

Entries the reference sets to Constants.HIDDEN_INFO are deliberately '?' there,
which is already what the Kotlin fallback produces, so they are skipped rather
than emitted.

Writes tracker-gba/src/main/kotlin/com/ironmonone/tracker/Gen3Charmap.kt.
Re-run if the reference tracker is ever updated.
"""
import io
import os
import re

BS = chr(92)
Q = chr(39)
DQ = chr(34)

REF = os.path.join(
    os.path.expanduser("~"), "ironmon-ref", "Ironmon-Tracker",
    "ironmon_tracker", "GameSettings.lua")
OUT = os.path.join(
    "tracker-gba", "src", "main", "kotlin", "com", "ironmonone", "tracker",
    "Gen3Charmap.kt")

src = io.open(REF, encoding="utf-8").read()

# [0xNN] = 'x',   or   [0xNN] = "x",
pattern = (r"[" + BS + "[]0x([0-9A-Fa-f]{2})" + BS + r"]" + BS + r"s*=" +
           BS + r"s*(" + Q + r"[^" + Q + r"]*" + Q + r"|" + DQ +
           r"[^" + DQ + r"]*" + DQ + r")" + BS + r"s*,")

seen = {}
for m in re.finditer(pattern, src):
    raw = m.group(2)[1:-1]
    if not raw:
        continue
    seen.setdefault(int(m.group(1), 16), raw)


def esc(s):
    out = ""
    for ch in s:
        printable = 32 <= ord(ch) < 127 and ch not in (BS + DQ + "$")
        out += ch if printable else BS + "u%04X" % ord(ch)
    return out


rows = ["        put(0x%02X, %s%s%s)" % (k, DQ, esc(seen[k]), DQ)
        for k in sorted(seen)]

header = '''package com.ironmonone.tracker

/**
 * Gen III character map, GENERATED by tools/extract_charmap.py from the PC
 * tracker's own table in GameSettings.lua. Do not hand-edit.
 *
 * Values are Strings, not Chars: several game bytes expand to more than one
 * character (0x34 is "LV", 0x53 is "PK", 0x54 is "MN").
 *
 * Bytes absent here fall through to "?" in Gen3Text.decode, which is exactly
 * what the reference does for them - it maps its own unprintables to
 * Constants.HIDDEN_INFO, and that constant is "?".
 */
internal object Gen3Charmap {
    val MAP: Map<Int, String> = HashMap<Int, String>().apply {
'''
footer = '''    }
}
'''

io.open(OUT, "w", encoding="utf-8", newline="\n").write(
    header + "\n".join(rows) + "\n" + footer)
print("%s: %d entries" % (OUT, len(rows)))
print("  0x1B ->", seen.get(0x1B))
